// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! This domain exposes CSS read/write operations. All CSS objects
//! (stylesheets, rules, and styles) have an associated `id` used in
//! subsequent operations on the related object. Each object type has a
//! specific `id` structure, and those are not interchangeable between objects
//! of different kinds. CSS objects can be loaded using the `get*ForNode()`
//! calls (which accept a DOM node id). A client can also keep track of
//! stylesheets via the `styleSheetAdded`/`styleSheetRemoved` events and
//! subsequently load the required stylesheet contents using the
//! `getStyleSheet\[Text\]()` methods.
//!
//! Types, command parameters and event payloads for the `CSS`
//! domain. The method-name constants for the same domain are in
//! [`crate::methods`].
//!
//! This domain is experimental and may change without notice.

use serde::{Deserialize, Serialize};

/// Stylesheet type: "injected" for stylesheets injected via extension,
/// "user-agent" for user-agent stylesheets, "inspector" for stylesheets
/// created by the inspector (i.e. those holding the "via inspector" rules),
/// "regular" for regular stylesheets.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum StyleSheetOrigin {
    /// `injected`
    #[serde(rename = "injected")]
    Injected,
    /// `user-agent`
    #[serde(rename = "user-agent")]
    UserAgent,
    /// `inspector`
    #[serde(rename = "inspector")]
    Inspector,
    /// `regular`
    #[serde(rename = "regular")]
    Regular,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// CSS rule collection for a single pseudo style.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PseudoElementMatches {
    /// Pseudo element type.
    #[serde(rename = "pseudoType")]
    pub pseudo_type: crate::protocol::dom::PseudoType,
    /// Pseudo element custom ident.
    #[serde(
        rename = "pseudoIdentifier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pseudo_identifier: Option<String>,
    /// Matches of CSS rules applicable to the pseudo style.
    pub matches: Vec<RuleMatch>,
}

/// CSS style coming from animations with the name of the animation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssAnimationStyle {
    /// The name of the animation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The style coming from the animation.
    pub style: CssStyle,
}

/// Inherited CSS rule collection from ancestor node.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct InheritedStyleEntry {
    /// The ancestor node's inline style, if any, in the style inheritance chain.
    #[serde(
        rename = "inlineStyle",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inline_style: Option<CssStyle>,
    /// Matches of CSS rules matching the ancestor node in the style inheritance
    /// chain.
    #[serde(rename = "matchedCSSRules")]
    pub matched_css_rules: Vec<RuleMatch>,
}

/// Inherited CSS style collection for animated styles from ancestor node.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct InheritedAnimatedStyleEntry {
    /// Styles coming from the animations of the ancestor, if any, in the style
    /// inheritance chain.
    #[serde(
        rename = "animationStyles",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub animation_styles: Option<Vec<CssAnimationStyle>>,
    /// The style coming from the transitions of the ancestor, if any, in the
    /// style inheritance chain.
    #[serde(
        rename = "transitionsStyle",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub transitions_style: Option<CssStyle>,
}

/// Inherited pseudo element matches from pseudos of an ancestor node.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct InheritedPseudoElementMatches {
    /// Matches of pseudo styles from the pseudos of an ancestor node.
    #[serde(rename = "pseudoElements")]
    pub pseudo_elements: Vec<PseudoElementMatches>,
}

/// Match data for a CSS rule.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RuleMatch {
    /// CSS rule in the match.
    pub rule: CssRule,
    /// Matching selector indices in the rule's selectorList selectors (0-based).
    #[serde(rename = "matchingSelectors")]
    pub matching_selectors: Vec<i64>,
}

/// Data for a simple selector (these are delimited by commas in a selector
/// list).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Value {
    /// Value text.
    pub text: String,
    /// Value range in the underlying resource (if available).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<SourceRange>,
    /// Specificity of the selector.
    ///
    /// Experimental: may change without notice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub specificity: Option<Specificity>,
}

/// Contribution of an individual simple selector to specificity.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SpecificityComponent {
    /// The simple selector text that contributes to specificity.
    pub text: String,
    /// The a component contribution.
    pub a: i64,
    /// The b component contribution.
    pub b: i64,
    /// The c component contribution.
    pub c: i64,
}

/// Specificity: <https://drafts.csswg.org/selectors/#specificity-rules>
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Specificity {
    /// The a component, which represents the number of ID selectors.
    pub a: i64,
    /// The b component, which represents the number of class selectors,
    /// attributes selectors, and pseudo-classes.
    pub b: i64,
    /// The c component, which represents the number of type selectors and
    /// pseudo-elements.
    pub c: i64,
    /// Per-simple-selector contributions used to explain this specificity.
    ///
    /// Experimental: may change without notice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub components: Option<Vec<SpecificityComponent>>,
}

/// Selector list data.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SelectorList {
    /// Selectors in the list.
    pub selectors: Vec<Value>,
    /// Rule selector text.
    pub text: String,
}

/// CSS stylesheet metainformation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CssStyleSheetHeader {
    /// The stylesheet identifier.
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    /// Owner frame identifier.
    #[serde(rename = "frameId")]
    pub frame_id: crate::protocol::page::FrameId,
    /// Stylesheet resource URL. Empty if this is a constructed stylesheet created
    /// using new CSSStyleSheet() (but non-empty if this is a constructed
    /// stylesheet imported as a CSS module script).
    #[serde(rename = "sourceURL")]
    pub source_url: String,
    /// URL of source map associated with the stylesheet (if any).
    #[serde(
        rename = "sourceMapURL",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_map_url: Option<String>,
    /// Stylesheet origin.
    pub origin: StyleSheetOrigin,
    /// Stylesheet title.
    pub title: String,
    /// The backend id for the owner node of the stylesheet.
    #[serde(rename = "ownerNode", default, skip_serializing_if = "Option::is_none")]
    pub owner_node: Option<crate::protocol::dom::BackendNodeId>,
    /// Denotes whether the stylesheet is disabled.
    pub disabled: bool,
    /// Whether the sourceURL field value comes from the sourceURL comment.
    #[serde(
        rename = "hasSourceURL",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub has_source_url: Option<bool>,
    /// Whether this stylesheet is created for STYLE tag by parser. This flag is
    /// not set for document.written STYLE tags.
    #[serde(rename = "isInline")]
    pub is_inline: bool,
    /// Whether this stylesheet is mutable. Inline stylesheets become mutable
    /// after they have been modified via CSSOM API. `\<link\>` element's
    /// stylesheets become mutable only if DevTools modifies them. Constructed
    /// stylesheets (new CSSStyleSheet()) are mutable immediately after creation.
    #[serde(rename = "isMutable")]
    pub is_mutable: bool,
    /// True if this stylesheet is created through new CSSStyleSheet() or imported
    /// as a CSS module script.
    #[serde(rename = "isConstructed")]
    pub is_constructed: bool,
    /// Line offset of the stylesheet within the resource (zero based).
    #[serde(rename = "startLine")]
    pub start_line: f64,
    /// Column offset of the stylesheet within the resource (zero based).
    #[serde(rename = "startColumn")]
    pub start_column: f64,
    /// Size of the content (in characters).
    pub length: f64,
    /// Line offset of the end of the stylesheet within the resource (zero based).
    #[serde(rename = "endLine")]
    pub end_line: f64,
    /// Column offset of the end of the stylesheet within the resource (zero
    /// based).
    #[serde(rename = "endColumn")]
    pub end_column: f64,
    /// If the style sheet was loaded from a network resource, this indicates when
    /// the resource failed to load
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "loadingFailed",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub loading_failed: Option<bool>,
}

/// CSS rule representation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CssRule {
    /// The css style sheet identifier (absent for user agent stylesheet and
    /// user-specified stylesheet rules) this rule came from.
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
    /// Rule selector data.
    #[serde(rename = "selectorList")]
    pub selector_list: SelectorList,
    /// Array of selectors from ancestor style rules, sorted by distance from the
    /// current rule.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "nestingSelectors",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub nesting_selectors: Option<Vec<String>>,
    /// Parent stylesheet's origin.
    pub origin: StyleSheetOrigin,
    /// Associated style declaration.
    pub style: CssStyle,
    /// The BackendNodeId of the DOM node that constitutes the origin tree scope
    /// of this rule.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "originTreeScopeNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub origin_tree_scope_node_id: Option<crate::protocol::dom::BackendNodeId>,
    /// Media list array (for rules involving media queries). The array enumerates
    /// media queries starting with the innermost one, going outwards.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media: Option<Vec<CssMedia>>,
    /// Container query list array (for rules involving container queries). The
    /// array enumerates container queries starting with the innermost one, going
    /// outwards.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "containerQueries",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub container_queries: Option<Vec<CssContainerQuery>>,
    /// @supports CSS at-rule array. The array enumerates @supports at-rules
    /// starting with the innermost one, going outwards.
    ///
    /// Experimental: may change without notice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supports: Option<Vec<CssSupports>>,
    /// Cascade layer array. Contains the layer hierarchy that this rule belongs
    /// to starting with the innermost layer and going outwards.
    ///
    /// Experimental: may change without notice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub layers: Option<Vec<CssLayer>>,
    /// @scope CSS at-rule array. The array enumerates @scope at-rules starting
    /// with the innermost one, going outwards.
    ///
    /// Experimental: may change without notice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<CssScope>>,
    /// The array keeps the types of ancestor CSSRules from the innermost going
    /// outwards.
    ///
    /// Experimental: may change without notice.
    #[serde(rename = "ruleTypes", default, skip_serializing_if = "Option::is_none")]
    pub rule_types: Option<Vec<CssRuleType>>,
    /// @starting-style CSS at-rule array. The array enumerates @starting-style
    /// at-rules starting with the innermost one, going outwards.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "startingStyles",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub starting_styles: Option<Vec<CssStartingStyle>>,
    /// @navigation CSS at-rule array. The array enumerates @navigation at-rules
    /// starting with the innermost one, going outwards.
    ///
    /// Experimental: may change without notice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub navigations: Option<Vec<CssNavigation>>,
}

/// Enum indicating the type of a CSS rule, used to represent the order of a
/// style rule's ancestors. This list only contains rule types that are
/// collected during the ancestor rule collection.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CssRuleType {
    /// `MediaRule`
    MediaRule,
    /// `SupportsRule`
    SupportsRule,
    /// `ContainerRule`
    ContainerRule,
    /// `LayerRule`
    LayerRule,
    /// `ScopeRule`
    ScopeRule,
    /// `StyleRule`
    StyleRule,
    /// `StartingStyleRule`
    StartingStyleRule,
    /// `NavigationRule`
    NavigationRule,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// CSS coverage information.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RuleUsage {
    /// The css style sheet identifier (absent for user agent stylesheet and
    /// user-specified stylesheet rules) this rule came from.
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    /// Offset of the start of the rule (including selector) from the beginning of
    /// the stylesheet.
    #[serde(rename = "startOffset")]
    pub start_offset: f64,
    /// Offset of the end of the rule body from the beginning of the stylesheet.
    #[serde(rename = "endOffset")]
    pub end_offset: f64,
    /// Indicates whether the rule was actually used by some element in the page.
    pub used: bool,
}

/// Text range within a resource. All numbers are zero-based.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SourceRange {
    /// Start line of range.
    #[serde(rename = "startLine")]
    pub start_line: i64,
    /// Start column of range (inclusive).
    #[serde(rename = "startColumn")]
    pub start_column: i64,
    /// End line of range
    #[serde(rename = "endLine")]
    pub end_line: i64,
    /// End column of range (exclusive).
    #[serde(rename = "endColumn")]
    pub end_column: i64,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ShorthandEntry {
    /// Shorthand name.
    pub name: String,
    /// Shorthand value.
    pub value: String,
    /// Whether the property has "!important" annotation (implies `false` if
    /// absent).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub important: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssComputedStyleProperty {
    /// Computed style property name.
    pub name: String,
    /// Computed style property value.
    pub value: String,
}

/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ComputedStyleExtraFields {
    /// Returns whether or not this node is being rendered with base appearance,
    /// which happens when it has its appearance property set to base/base-select
    /// or it is in the subtree of an element being rendered with base appearance.
    #[serde(rename = "isAppearanceBase")]
    pub is_appearance_base: bool,
}

/// CSS style representation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssStyle {
    /// The css style sheet identifier (absent for user agent stylesheet and
    /// user-specified stylesheet rules) this rule came from.
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
    /// CSS properties in the style.
    #[serde(rename = "cssProperties")]
    pub css_properties: Vec<CssProperty>,
    /// Computed values for all shorthands found in the style.
    #[serde(rename = "shorthandEntries")]
    pub shorthand_entries: Vec<ShorthandEntry>,
    /// Style declaration text (if available).
    #[serde(rename = "cssText", default, skip_serializing_if = "Option::is_none")]
    pub css_text: Option<String>,
    /// Style declaration range in the enclosing stylesheet (if available).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<SourceRange>,
}

/// CSS property declaration data.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssProperty {
    /// The property name.
    pub name: String,
    /// The property value.
    pub value: String,
    /// Whether the property has "!important" annotation (implies `false` if
    /// absent).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub important: Option<bool>,
    /// Whether the property is implicit (implies `false` if absent).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub implicit: Option<bool>,
    /// The full property text as specified in the style.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Whether the property is understood by the browser (implies `true` if
    /// absent).
    #[serde(rename = "parsedOk", default, skip_serializing_if = "Option::is_none")]
    pub parsed_ok: Option<bool>,
    /// Whether the property is disabled by the user (present for source-based
    /// properties only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    /// The entire property range in the enclosing style declaration (if
    /// available).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<SourceRange>,
    /// Parsed longhand components of this property if it is a shorthand. This
    /// field will be empty if the given property is not a shorthand.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "longhandProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub longhand_properties: Option<Vec<CssProperty>>,
}

/// CSS media rule descriptor.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CssMedia {
    /// Media query text.
    pub text: String,
    /// Source of the media query: "mediaRule" if specified by a @media rule,
    /// "importRule" if specified by an @import rule, "linkedSheet" if specified
    /// by a "media" attribute in a linked stylesheet's LINK tag, "inlineSheet" if
    /// specified by a "media" attribute in an inline stylesheet's STYLE tag.
    pub source: CssMediaSource,
    /// URL of the document containing the media query description.
    #[serde(rename = "sourceURL", default, skip_serializing_if = "Option::is_none")]
    pub source_url: Option<String>,
    /// The associated rule (@media or @import) header range in the enclosing
    /// stylesheet (if available).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<SourceRange>,
    /// Identifier of the stylesheet containing this object (if exists).
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
    /// Array of media queries.
    #[serde(rename = "mediaList", default, skip_serializing_if = "Option::is_none")]
    pub media_list: Option<Vec<MediaQuery>>,
}

/// The values `source` accepts on `CSSMedia`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CssMediaSource {
    /// `mediaRule`
    #[serde(rename = "mediaRule")]
    MediaRule,
    /// `importRule`
    #[serde(rename = "importRule")]
    ImportRule,
    /// `linkedSheet`
    #[serde(rename = "linkedSheet")]
    LinkedSheet,
    /// `inlineSheet`
    #[serde(rename = "inlineSheet")]
    InlineSheet,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Media query descriptor.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MediaQuery {
    /// Array of media query expressions.
    pub expressions: Vec<MediaQueryExpression>,
    /// Whether the media query condition is satisfied.
    pub active: bool,
}

/// Media query expression descriptor.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MediaQueryExpression {
    /// Media query expression value.
    pub value: f64,
    /// Media query expression units.
    pub unit: String,
    /// Media query expression feature.
    pub feature: String,
    /// The associated range of the value text in the enclosing stylesheet (if
    /// available).
    #[serde(
        rename = "valueRange",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub value_range: Option<SourceRange>,
    /// Computed length of media query expression (if applicable).
    #[serde(
        rename = "computedLength",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub computed_length: Option<f64>,
}

/// CSS container query rule descriptor.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssContainerQuery {
    /// Container query text. Contains the query part without the container name
    /// for a single query. Deprecated in favor of conditionText which contains
    /// the full prelude after @container.
    ///
    /// Deprecated in the protocol.
    pub text: String,
    /// The associated rule header range in the enclosing stylesheet (if
    /// available).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<SourceRange>,
    /// Identifier of the stylesheet containing this object (if exists).
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
    /// Optional name for the container.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Optional physical axes queried for the container.
    #[serde(
        rename = "physicalAxes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub physical_axes: Option<crate::protocol::dom::PhysicalAxes>,
    /// Optional logical axes queried for the container.
    #[serde(
        rename = "logicalAxes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub logical_axes: Option<crate::protocol::dom::LogicalAxes>,
    /// true if the query contains scroll-state() queries.
    #[serde(
        rename = "queriesScrollState",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub queries_scroll_state: Option<bool>,
    /// true if the query contains anchored() queries.
    #[serde(
        rename = "queriesAnchored",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub queries_anchored: Option<bool>,
    /// CSSContainerRule.conditionText
    #[serde(rename = "conditionText")]
    pub condition_text: String,
}

/// CSS Supports at-rule descriptor.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssSupports {
    /// Supports rule text.
    pub text: String,
    /// Whether the supports condition is satisfied.
    pub active: bool,
    /// The associated rule header range in the enclosing stylesheet (if
    /// available).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<SourceRange>,
    /// Identifier of the stylesheet containing this object (if exists).
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
}

/// CSS Navigation at-rule descriptor.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssNavigation {
    /// Navigation rule text.
    pub text: String,
    /// Whether the navigation condition is satisfied.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// The associated rule header range in the enclosing stylesheet (if
    /// available).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<SourceRange>,
    /// Identifier of the stylesheet containing this object (if exists).
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
}

/// CSS Scope at-rule descriptor.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssScope {
    /// Scope rule text.
    pub text: String,
    /// The associated rule header range in the enclosing stylesheet (if
    /// available).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<SourceRange>,
    /// Identifier of the stylesheet containing this object (if exists).
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
}

/// CSS Layer at-rule descriptor.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssLayer {
    /// Layer name.
    pub text: String,
    /// The associated rule header range in the enclosing stylesheet (if
    /// available).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<SourceRange>,
    /// Identifier of the stylesheet containing this object (if exists).
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
}

/// CSS Starting Style at-rule descriptor.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssStartingStyle {
    /// The associated rule header range in the enclosing stylesheet (if
    /// available).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<SourceRange>,
    /// Identifier of the stylesheet containing this object (if exists).
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
}

/// CSS Layer data.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssLayerData {
    /// Layer name.
    pub name: String,
    /// Direct sub-layers
    #[serde(rename = "subLayers", default, skip_serializing_if = "Option::is_none")]
    pub sub_layers: Option<Vec<CssLayerData>>,
    /// Layer order. The order determines the order of the layer in the cascade
    /// order. A higher number has higher priority in the cascade order.
    pub order: f64,
}

/// Information about amount of glyphs that were rendered with given font.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PlatformFontUsage {
    /// Font's family name reported by platform.
    #[serde(rename = "familyName")]
    pub family_name: String,
    /// Font's PostScript name reported by platform.
    #[serde(rename = "postScriptName")]
    pub post_script_name: String,
    /// Indicates if the font was downloaded or resolved locally.
    #[serde(rename = "isCustomFont")]
    pub is_custom_font: bool,
    /// Amount of glyphs that were rendered with this font.
    #[serde(rename = "glyphCount")]
    pub glyph_count: f64,
}

/// Information about font variation axes for variable fonts
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FontVariationAxis {
    /// The font-variation-setting tag (a.k.a. "axis tag").
    pub tag: String,
    /// Human-readable variation name in the default language (normally, "en").
    pub name: String,
    /// The minimum value (inclusive) the font supports for this tag.
    #[serde(rename = "minValue")]
    pub min_value: f64,
    /// The maximum value (inclusive) the font supports for this tag.
    #[serde(rename = "maxValue")]
    pub max_value: f64,
    /// The default value.
    #[serde(rename = "defaultValue")]
    pub default_value: f64,
}

/// Properties of a web font:
/// <https://www.w3.org/TR/2008/REC-CSS2-20080411/fonts.html#font-descriptions>
/// and additional information such as platformFontFamily and
/// fontVariationAxes.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FontFace {
    /// The font-family.
    #[serde(rename = "fontFamily")]
    pub font_family: String,
    /// The font-style.
    #[serde(rename = "fontStyle")]
    pub font_style: String,
    /// The font-variant.
    #[serde(rename = "fontVariant")]
    pub font_variant: String,
    /// The font-weight.
    #[serde(rename = "fontWeight")]
    pub font_weight: String,
    /// The font-stretch.
    #[serde(rename = "fontStretch")]
    pub font_stretch: String,
    /// The font-display.
    #[serde(rename = "fontDisplay")]
    pub font_display: String,
    /// The unicode-range.
    #[serde(rename = "unicodeRange")]
    pub unicode_range: String,
    /// The src.
    pub src: String,
    /// The resolved platform font family
    #[serde(rename = "platformFontFamily")]
    pub platform_font_family: String,
    /// Available variation settings (a.k.a. "axes").
    #[serde(
        rename = "fontVariationAxes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub font_variation_axes: Option<Vec<FontVariationAxis>>,
}

/// CSS try rule representation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CssTryRule {
    /// The css style sheet identifier (absent for user agent stylesheet and
    /// user-specified stylesheet rules) this rule came from.
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
    /// Parent stylesheet's origin.
    pub origin: StyleSheetOrigin,
    /// Associated style declaration.
    pub style: CssStyle,
}

/// CSS @position-try rule representation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CssPositionTryRule {
    /// The prelude dashed-ident name
    pub name: Value,
    /// The css style sheet identifier (absent for user agent stylesheet and
    /// user-specified stylesheet rules) this rule came from.
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
    /// Parent stylesheet's origin.
    pub origin: StyleSheetOrigin,
    /// Associated style declaration.
    pub style: CssStyle,
    pub active: bool,
}

/// CSS keyframes rule representation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssKeyframesRule {
    /// Animation name.
    #[serde(rename = "animationName")]
    pub animation_name: Value,
    /// List of keyframes.
    pub keyframes: Vec<CssKeyframeRule>,
}

/// Representation of a custom property registration through
/// CSS.registerProperty
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssPropertyRegistration {
    #[serde(rename = "propertyName")]
    pub property_name: String,
    #[serde(
        rename = "initialValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub initial_value: Option<Value>,
    pub inherits: bool,
    pub syntax: String,
}

/// CSS generic @rule representation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CssAtRule {
    /// Type of at-rule.
    pub r#type: CssAtRuleType,
    /// Subsection of font-feature-values, if this is a subsection.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subsection: Option<CssAtRuleSubsection>,
    /// LINT.ThenChange(//third_party/blink/renderer/core/inspector/inspector_style_sheet.cc:FontVariantAlternatesFeatureType,//third_party/blink/renderer/core/inspector/inspector_css_agent.cc:FontVariantAlternatesFeatureType)
    /// Associated name, if applicable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<Value>,
    /// The css style sheet identifier (absent for user agent stylesheet and
    /// user-specified stylesheet rules) this rule came from.
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
    /// Parent stylesheet's origin.
    pub origin: StyleSheetOrigin,
    /// Associated style declaration.
    pub style: CssStyle,
}

/// The values `type` accepts on `CSSAtRule`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CssAtRuleType {
    /// `font-face`
    #[serde(rename = "font-face")]
    FontFace,
    /// `font-feature-values`
    #[serde(rename = "font-feature-values")]
    FontFeatureValues,
    /// `font-palette-values`
    #[serde(rename = "font-palette-values")]
    FontPaletteValues,
    /// `counter-style`
    #[serde(rename = "counter-style")]
    CounterStyle,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// The values `subsection` accepts on `CSSAtRule`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CssAtRuleSubsection {
    /// `swash`
    #[serde(rename = "swash")]
    Swash,
    /// `annotation`
    #[serde(rename = "annotation")]
    Annotation,
    /// `ornaments`
    #[serde(rename = "ornaments")]
    Ornaments,
    /// `stylistic`
    #[serde(rename = "stylistic")]
    Stylistic,
    /// `styleset`
    #[serde(rename = "styleset")]
    Styleset,
    /// `character-variant`
    #[serde(rename = "character-variant")]
    CharacterVariant,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// CSS property at-rule representation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CssPropertyRule {
    /// The css style sheet identifier (absent for user agent stylesheet and
    /// user-specified stylesheet rules) this rule came from.
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
    /// Parent stylesheet's origin.
    pub origin: StyleSheetOrigin,
    /// Associated property name.
    #[serde(rename = "propertyName")]
    pub property_name: Value,
    /// Associated style declaration.
    pub style: CssStyle,
}

/// CSS function argument representation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssFunctionParameter {
    /// The parameter name.
    pub name: String,
    /// The parameter type.
    pub r#type: String,
}

/// CSS function conditional block representation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssFunctionConditionNode {
    /// Media query for this conditional block. Only one type of condition should
    /// be set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media: Option<CssMedia>,
    /// Container query for this conditional block. Only one type of condition
    /// should be set.
    #[serde(
        rename = "containerQueries",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub container_queries: Option<CssContainerQuery>,
    /// @supports CSS at-rule condition. Only one type of condition should be set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supports: Option<CssSupports>,
    /// @navigation condition. Only one type of condition should be set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub navigation: Option<CssNavigation>,
    /// Block body.
    pub children: Vec<CssFunctionNode>,
    /// The condition text.
    #[serde(rename = "conditionText")]
    pub condition_text: String,
}

/// Section of the body of a CSS function rule.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CssFunctionNode {
    /// A conditional block. If set, style should not be set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub condition: Option<CssFunctionConditionNode>,
    /// Values set by this node. If set, condition should not be set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<CssStyle>,
}

/// CSS function at-rule representation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CssFunctionRule {
    /// Name of the function.
    pub name: Value,
    /// The css style sheet identifier (absent for user agent stylesheet and
    /// user-specified stylesheet rules) this rule came from.
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
    /// Parent stylesheet's origin.
    pub origin: StyleSheetOrigin,
    /// List of parameters.
    pub parameters: Vec<CssFunctionParameter>,
    /// Function body.
    pub children: Vec<CssFunctionNode>,
    /// The BackendNodeId of the DOM node that constitutes the origin tree scope
    /// of this rule.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "originTreeScopeNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub origin_tree_scope_node_id: Option<crate::protocol::dom::BackendNodeId>,
}

/// CSS keyframe rule representation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CssKeyframeRule {
    /// The css style sheet identifier (absent for user agent stylesheet and
    /// user-specified stylesheet rules) this rule came from.
    #[serde(
        rename = "styleSheetId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub style_sheet_id: Option<crate::protocol::dom::StyleSheetId>,
    /// Parent stylesheet's origin.
    pub origin: StyleSheetOrigin,
    /// Associated key text.
    #[serde(rename = "keyText")]
    pub key_text: Value,
    /// Associated style declaration.
    pub style: CssStyle,
}

/// A descriptor of operation to mutate style declaration text.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StyleDeclarationEdit {
    /// The css style sheet identifier.
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    /// The range of the style text in the enclosing stylesheet.
    pub range: SourceRange,
    /// New style text.
    pub text: String,
}

/// Inserts a new rule with the given `ruleText` in a stylesheet with given
/// `styleSheetId`, at the position specified by `location`.
///
/// Parameters of `CSS.addRule`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AddRuleParams {
    /// The css style sheet identifier where a new rule should be inserted.
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    /// The text of a new rule.
    #[serde(rename = "ruleText")]
    pub rule_text: String,
    /// Text position of a new rule in the target style sheet.
    pub location: SourceRange,
    /// NodeId for the DOM node in whose context custom property declarations for
    /// registered properties should be validated. If omitted, declarations in the
    /// new rule text can only be validated statically, which may produce
    /// incorrect results if the declaration contains a var() for example.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "nodeForPropertySyntaxValidation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub node_for_property_syntax_validation: Option<crate::protocol::dom::NodeId>,
}

/// What `CSS.addRule` answers with.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddRuleReturns {
    /// The newly created rule.
    pub rule: CssRule,
}

impl crate::typed::Command for AddRuleParams {
    const METHOD: &'static str = "CSS.addRule";
    type Returns = AddRuleReturns;
}

/// Returns all class names from specified stylesheet.
///
/// Parameters of `CSS.collectClassNames`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CollectClassNamesParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
}

/// What `CSS.collectClassNames` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CollectClassNamesReturns {
    /// Class name list.
    #[serde(rename = "classNames")]
    pub class_names: Vec<String>,
}

impl crate::typed::Command for CollectClassNamesParams {
    const METHOD: &'static str = "CSS.collectClassNames";
    type Returns = CollectClassNamesReturns;
}

/// Creates a new special "via-inspector" stylesheet in the frame with given
/// `frameId`.
///
/// Parameters of `CSS.createStyleSheet`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CreateStyleSheetParams {
    /// Identifier of the frame where "via-inspector" stylesheet should be
    /// created.
    #[serde(rename = "frameId")]
    pub frame_id: crate::protocol::page::FrameId,
    /// If true, creates a new stylesheet for every call. If false, returns a
    /// stylesheet previously created by a call with force=false for the frame's
    /// document if it exists or creates a new stylesheet (default: false).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

/// What `CSS.createStyleSheet` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CreateStyleSheetReturns {
    /// Identifier of the created "via-inspector" stylesheet.
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
}

impl crate::typed::Command for CreateStyleSheetParams {
    const METHOD: &'static str = "CSS.createStyleSheet";
    type Returns = CreateStyleSheetReturns;
}

/// Disables the CSS agent for the given page.
///
/// Parameters of `CSS.disable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DisableParams {}

impl crate::typed::Command for DisableParams {
    const METHOD: &'static str = "CSS.disable";
    type Returns = crate::typed::NoReturns;
}

/// Enables the CSS agent for the given page. Clients should not assume that
/// the CSS agent has been enabled until the result of this command is
/// received.
///
/// Parameters of `CSS.enable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnableParams {}

impl crate::typed::Command for EnableParams {
    const METHOD: &'static str = "CSS.enable";
    type Returns = crate::typed::NoReturns;
}

/// Ensures that the given node will have specified pseudo-classes whenever
/// its style is computed by the browser.
///
/// Parameters of `CSS.forcePseudoState`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ForcePseudoStateParams {
    /// The element id for which to force the pseudo state.
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
    /// Element pseudo classes to force when computing the element's style.
    #[serde(rename = "forcedPseudoClasses")]
    pub forced_pseudo_classes: Vec<String>,
}

impl crate::typed::Command for ForcePseudoStateParams {
    const METHOD: &'static str = "CSS.forcePseudoState";
    type Returns = crate::typed::NoReturns;
}

/// Ensures that the given node is in its starting-style state.
///
/// Parameters of `CSS.forceStartingStyle`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ForceStartingStyleParams {
    /// The element id for which to force the starting-style state.
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
    /// Boolean indicating if this is on or off.
    pub forced: bool,
}

impl crate::typed::Command for ForceStartingStyleParams {
    const METHOD: &'static str = "CSS.forceStartingStyle";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `CSS.getBackgroundColors`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetBackgroundColorsParams {
    /// Id of the node to get background colors for.
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
}

/// What `CSS.getBackgroundColors` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetBackgroundColorsReturns {
    /// The range of background colors behind this element, if it contains any
    /// visible text. If no visible text is present, this will be undefined. In
    /// the case of a flat background color, this will consist of simply that
    /// color. In the case of a gradient, this will consist of each of the color
    /// stops. For anything more complicated, this will be an empty array. Images
    /// will be ignored (as if the image had failed to load).
    #[serde(
        rename = "backgroundColors",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub background_colors: Option<Vec<String>>,
    /// The computed font size for this node, as a CSS computed value string (e.g.
    /// '12px').
    #[serde(
        rename = "computedFontSize",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub computed_font_size: Option<String>,
    /// The computed font weight for this node, as a CSS computed value string
    /// (e.g. 'normal' or '100').
    #[serde(
        rename = "computedFontWeight",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub computed_font_weight: Option<String>,
}

impl crate::typed::Command for GetBackgroundColorsParams {
    const METHOD: &'static str = "CSS.getBackgroundColors";
    type Returns = GetBackgroundColorsReturns;
}

/// Returns the computed style for a DOM node identified by `nodeId`.
///
/// Parameters of `CSS.getComputedStyleForNode`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetComputedStyleForNodeParams {
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
}

/// What `CSS.getComputedStyleForNode` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetComputedStyleForNodeReturns {
    /// Computed style for the specified DOM node.
    #[serde(rename = "computedStyle")]
    pub computed_style: Vec<CssComputedStyleProperty>,
    /// A list of non-standard "extra fields" which blink stores alongside each
    /// computed style.
    ///
    /// Experimental: may change without notice.
    #[serde(rename = "extraFields")]
    pub extra_fields: ComputedStyleExtraFields,
}

impl crate::typed::Command for GetComputedStyleForNodeParams {
    const METHOD: &'static str = "CSS.getComputedStyleForNode";
    type Returns = GetComputedStyleForNodeReturns;
}

/// Resolve the specified values in the context of the provided element. For
/// example, a value of '1em' is evaluated according to the computed
/// 'font-size' of the element and a value 'calc(1px + 2px)' will be resolved
/// to '3px'. If the `propertyName` was specified the `values` are resolved as
/// if they were property's declaration. If a value cannot be parsed according
/// to the provided property syntax, the value is parsed using combined syntax
/// as if null `propertyName` was provided. If the value cannot be resolved
/// even then, return the provided value without any changes. Note: this
/// function currently does not resolve CSS random() function, it returns
/// unmodified random() function parts.`
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.resolveValues`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ResolveValuesParams {
    /// Cascade-dependent keywords (revert/revert-layer) do not work.
    pub values: Vec<String>,
    /// Id of the node in whose context the expression is evaluated
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
    /// Only longhands and custom property names are accepted.
    #[serde(
        rename = "propertyName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub property_name: Option<String>,
    /// Pseudo element type, only works for pseudo elements that generate elements
    /// in the tree, such as ::before and ::after.
    #[serde(
        rename = "pseudoType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pseudo_type: Option<crate::protocol::dom::PseudoType>,
    /// Pseudo element custom ident.
    #[serde(
        rename = "pseudoIdentifier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pseudo_identifier: Option<String>,
}

/// What `CSS.resolveValues` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ResolveValuesReturns {
    pub results: Vec<String>,
}

impl crate::typed::Command for ResolveValuesParams {
    const METHOD: &'static str = "CSS.resolveValues";
    type Returns = ResolveValuesReturns;
}

/// Experimental: may change without notice.
///
/// Parameters of `CSS.getLonghandProperties`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetLonghandPropertiesParams {
    #[serde(rename = "shorthandName")]
    pub shorthand_name: String,
    pub value: String,
}

/// What `CSS.getLonghandProperties` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetLonghandPropertiesReturns {
    #[serde(rename = "longhandProperties")]
    pub longhand_properties: Vec<CssProperty>,
}

impl crate::typed::Command for GetLonghandPropertiesParams {
    const METHOD: &'static str = "CSS.getLonghandProperties";
    type Returns = GetLonghandPropertiesReturns;
}

/// Returns the styles defined inline (explicitly in the "style" attribute and
/// implicitly, using DOM attributes) for a DOM node identified by `nodeId`.
///
/// Parameters of `CSS.getInlineStylesForNode`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetInlineStylesForNodeParams {
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
}

/// What `CSS.getInlineStylesForNode` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetInlineStylesForNodeReturns {
    /// Inline style for the specified DOM node.
    #[serde(
        rename = "inlineStyle",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inline_style: Option<CssStyle>,
    /// Attribute-defined element style (e.g. resulting from "width=20
    /// height=100%").
    #[serde(
        rename = "attributesStyle",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub attributes_style: Option<CssStyle>,
}

impl crate::typed::Command for GetInlineStylesForNodeParams {
    const METHOD: &'static str = "CSS.getInlineStylesForNode";
    type Returns = GetInlineStylesForNodeReturns;
}

/// Returns the styles coming from animations & transitions including the
/// animation & transition styles coming from inheritance chain.
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.getAnimatedStylesForNode`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetAnimatedStylesForNodeParams {
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
}

/// What `CSS.getAnimatedStylesForNode` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetAnimatedStylesForNodeReturns {
    /// Styles coming from animations.
    #[serde(
        rename = "animationStyles",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub animation_styles: Option<Vec<CssAnimationStyle>>,
    /// Style coming from transitions.
    #[serde(
        rename = "transitionsStyle",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub transitions_style: Option<CssStyle>,
    /// Inherited style entries for animationsStyle and transitionsStyle from the
    /// inheritance chain of the element.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inherited: Option<Vec<InheritedAnimatedStyleEntry>>,
}

impl crate::typed::Command for GetAnimatedStylesForNodeParams {
    const METHOD: &'static str = "CSS.getAnimatedStylesForNode";
    type Returns = GetAnimatedStylesForNodeReturns;
}

/// Returns requested styles for a DOM node identified by `nodeId`.
///
/// Parameters of `CSS.getMatchedStylesForNode`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetMatchedStylesForNodeParams {
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
}

/// What `CSS.getMatchedStylesForNode` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetMatchedStylesForNodeReturns {
    /// Inline style for the specified DOM node.
    #[serde(
        rename = "inlineStyle",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inline_style: Option<CssStyle>,
    /// Attribute-defined element style (e.g. resulting from "width=20
    /// height=100%").
    #[serde(
        rename = "attributesStyle",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub attributes_style: Option<CssStyle>,
    /// CSS rules matching this node, from all applicable stylesheets.
    #[serde(
        rename = "matchedCSSRules",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub matched_css_rules: Option<Vec<RuleMatch>>,
    /// Pseudo style matches for this node.
    #[serde(
        rename = "pseudoElements",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pseudo_elements: Option<Vec<PseudoElementMatches>>,
    /// A chain of inherited styles (from the immediate node parent up to the DOM
    /// tree root).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inherited: Option<Vec<InheritedStyleEntry>>,
    /// A chain of inherited pseudo element styles (from the immediate node parent
    /// up to the DOM tree root).
    #[serde(
        rename = "inheritedPseudoElements",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inherited_pseudo_elements: Option<Vec<InheritedPseudoElementMatches>>,
    /// A list of CSS keyframed animations matching this node.
    #[serde(
        rename = "cssKeyframesRules",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub css_keyframes_rules: Option<Vec<CssKeyframesRule>>,
    /// A list of CSS @position-try rules matching this node, based on the
    /// position-try-fallbacks property.
    #[serde(
        rename = "cssPositionTryRules",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub css_position_try_rules: Option<Vec<CssPositionTryRule>>,
    /// Index of the active fallback in the applied position-try-fallback
    /// property, will not be set if there is no active position-try fallback.
    #[serde(
        rename = "activePositionFallbackIndex",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub active_position_fallback_index: Option<i64>,
    /// A list of CSS at-property rules matching this node.
    #[serde(
        rename = "cssPropertyRules",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub css_property_rules: Option<Vec<CssPropertyRule>>,
    /// A list of CSS property registrations matching this node.
    #[serde(
        rename = "cssPropertyRegistrations",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub css_property_registrations: Option<Vec<CssPropertyRegistration>>,
    /// A list of simple @rules matching this node or its pseudo-elements.
    #[serde(
        rename = "cssAtRules",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub css_at_rules: Option<Vec<CssAtRule>>,
    /// Id of the first parent element that does not have display: contents.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "parentLayoutNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_layout_node_id: Option<crate::protocol::dom::NodeId>,
    /// A list of CSS at-function rules referenced by styles of this node.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "cssFunctionRules",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub css_function_rules: Option<Vec<CssFunctionRule>>,
}

impl crate::typed::Command for GetMatchedStylesForNodeParams {
    const METHOD: &'static str = "CSS.getMatchedStylesForNode";
    type Returns = GetMatchedStylesForNodeReturns;
}

/// Returns the values of the default UA-defined environment variables used in
/// env()
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.getEnvironmentVariables`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetEnvironmentVariablesParams {}

/// What `CSS.getEnvironmentVariables` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetEnvironmentVariablesReturns {
    #[serde(rename = "environmentVariables")]
    pub environment_variables: serde_json::Value,
}

impl crate::typed::Command for GetEnvironmentVariablesParams {
    const METHOD: &'static str = "CSS.getEnvironmentVariables";
    type Returns = GetEnvironmentVariablesReturns;
}

/// Returns all media queries parsed by the rendering engine.
///
/// Parameters of `CSS.getMediaQueries`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetMediaQueriesParams {}

/// What `CSS.getMediaQueries` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetMediaQueriesReturns {
    pub medias: Vec<CssMedia>,
}

impl crate::typed::Command for GetMediaQueriesParams {
    const METHOD: &'static str = "CSS.getMediaQueries";
    type Returns = GetMediaQueriesReturns;
}

/// Requests information about platform fonts which we used to render child
/// TextNodes in the given node.
///
/// Parameters of `CSS.getPlatformFontsForNode`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetPlatformFontsForNodeParams {
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
}

/// What `CSS.getPlatformFontsForNode` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetPlatformFontsForNodeReturns {
    /// Usage statistics for every employed platform font.
    pub fonts: Vec<PlatformFontUsage>,
}

impl crate::typed::Command for GetPlatformFontsForNodeParams {
    const METHOD: &'static str = "CSS.getPlatformFontsForNode";
    type Returns = GetPlatformFontsForNodeReturns;
}

/// Returns the current textual content for a stylesheet.
///
/// Parameters of `CSS.getStyleSheetText`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetStyleSheetTextParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
}

/// What `CSS.getStyleSheetText` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetStyleSheetTextReturns {
    /// The stylesheet text.
    pub text: String,
}

impl crate::typed::Command for GetStyleSheetTextParams {
    const METHOD: &'static str = "CSS.getStyleSheetText";
    type Returns = GetStyleSheetTextReturns;
}

/// Returns all layers parsed by the rendering engine for the tree scope of a
/// node. Given a DOM element identified by nodeId, getLayersForNode returns
/// the root layer for the nearest ancestor document or shadow root. The layer
/// root contains the full layer tree for the tree scope and their ordering.
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.getLayersForNode`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetLayersForNodeParams {
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
}

/// What `CSS.getLayersForNode` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetLayersForNodeReturns {
    #[serde(rename = "rootLayer")]
    pub root_layer: CssLayerData,
}

impl crate::typed::Command for GetLayersForNodeParams {
    const METHOD: &'static str = "CSS.getLayersForNode";
    type Returns = GetLayersForNodeReturns;
}

/// Given a CSS selector text and a style sheet ID, getLocationForSelector
/// returns an array of locations of the CSS selector in the style sheet.
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.getLocationForSelector`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetLocationForSelectorParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    #[serde(rename = "selectorText")]
    pub selector_text: String,
}

/// What `CSS.getLocationForSelector` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetLocationForSelectorReturns {
    pub ranges: Vec<SourceRange>,
}

impl crate::typed::Command for GetLocationForSelectorParams {
    const METHOD: &'static str = "CSS.getLocationForSelector";
    type Returns = GetLocationForSelectorReturns;
}

/// Starts tracking the given node for the computed style updates and whenever
/// the computed style is updated for node, it queues a `computedStyleUpdated`
/// event with throttling. There can only be 1 node tracked for computed style
/// updates so passing a new node id removes tracking from the previous node.
/// Pass `undefined` to disable tracking.
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.trackComputedStyleUpdatesForNode`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TrackComputedStyleUpdatesForNodeParams {
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<crate::protocol::dom::NodeId>,
}

impl crate::typed::Command for TrackComputedStyleUpdatesForNodeParams {
    const METHOD: &'static str = "CSS.trackComputedStyleUpdatesForNode";
    type Returns = crate::typed::NoReturns;
}

/// Starts tracking the given computed styles for updates. The specified array
/// of properties replaces the one previously specified. Pass empty array to
/// disable tracking. Use takeComputedStyleUpdates to retrieve the list of
/// nodes that had properties modified. The changes to computed style
/// properties are only tracked for nodes pushed to the front-end by the DOM
/// agent. If no changes to the tracked properties occur after the node has
/// been pushed to the front-end, no updates will be issued for the node.
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.trackComputedStyleUpdates`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TrackComputedStyleUpdatesParams {
    #[serde(rename = "propertiesToTrack")]
    pub properties_to_track: Vec<CssComputedStyleProperty>,
}

impl crate::typed::Command for TrackComputedStyleUpdatesParams {
    const METHOD: &'static str = "CSS.trackComputedStyleUpdates";
    type Returns = crate::typed::NoReturns;
}

/// Polls the next batch of computed style updates.
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.takeComputedStyleUpdates`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TakeComputedStyleUpdatesParams {}

/// What `CSS.takeComputedStyleUpdates` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TakeComputedStyleUpdatesReturns {
    /// The list of node Ids that have their tracked computed styles updated.
    #[serde(rename = "nodeIds")]
    pub node_ids: Vec<crate::protocol::dom::NodeId>,
}

impl crate::typed::Command for TakeComputedStyleUpdatesParams {
    const METHOD: &'static str = "CSS.takeComputedStyleUpdates";
    type Returns = TakeComputedStyleUpdatesReturns;
}

/// Find a rule with the given active property for the given node and set the
/// new value for this property
///
/// Parameters of `CSS.setEffectivePropertyValueForNode`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetEffectivePropertyValueForNodeParams {
    /// The element id for which to set property.
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
    #[serde(rename = "propertyName")]
    pub property_name: String,
    pub value: String,
}

impl crate::typed::Command for SetEffectivePropertyValueForNodeParams {
    const METHOD: &'static str = "CSS.setEffectivePropertyValueForNode";
    type Returns = crate::typed::NoReturns;
}

/// Modifies the property rule property name.
///
/// Parameters of `CSS.setPropertyRulePropertyName`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetPropertyRulePropertyNameParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    pub range: SourceRange,
    #[serde(rename = "propertyName")]
    pub property_name: String,
}

/// What `CSS.setPropertyRulePropertyName` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetPropertyRulePropertyNameReturns {
    /// The resulting key text after modification.
    #[serde(rename = "propertyName")]
    pub property_name: Value,
}

impl crate::typed::Command for SetPropertyRulePropertyNameParams {
    const METHOD: &'static str = "CSS.setPropertyRulePropertyName";
    type Returns = SetPropertyRulePropertyNameReturns;
}

/// Modifies the keyframe rule key text.
///
/// Parameters of `CSS.setKeyframeKey`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetKeyframeKeyParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    pub range: SourceRange,
    #[serde(rename = "keyText")]
    pub key_text: String,
}

/// What `CSS.setKeyframeKey` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetKeyframeKeyReturns {
    /// The resulting key text after modification.
    #[serde(rename = "keyText")]
    pub key_text: Value,
}

impl crate::typed::Command for SetKeyframeKeyParams {
    const METHOD: &'static str = "CSS.setKeyframeKey";
    type Returns = SetKeyframeKeyReturns;
}

/// Modifies the rule selector.
///
/// Parameters of `CSS.setMediaText`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetMediaTextParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    pub range: SourceRange,
    pub text: String,
}

/// What `CSS.setMediaText` answers with.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetMediaTextReturns {
    /// The resulting CSS media rule after modification.
    pub media: CssMedia,
}

impl crate::typed::Command for SetMediaTextParams {
    const METHOD: &'static str = "CSS.setMediaText";
    type Returns = SetMediaTextReturns;
}

/// Modifies the expression of a container query. Deprecated. Use
/// setContainerQueryConditionText instead.
///
/// Deprecated in the protocol.
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.setContainerQueryText`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetContainerQueryTextParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    pub range: SourceRange,
    pub text: String,
}

/// What `CSS.setContainerQueryText` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetContainerQueryTextReturns {
    /// The resulting CSS container query rule after modification.
    #[serde(rename = "containerQuery")]
    pub container_query: CssContainerQuery,
}

impl crate::typed::Command for SetContainerQueryTextParams {
    const METHOD: &'static str = "CSS.setContainerQueryText";
    type Returns = SetContainerQueryTextReturns;
}

/// Experimental: may change without notice.
///
/// Parameters of `CSS.setContainerQueryConditionText`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetContainerQueryConditionTextParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    pub range: SourceRange,
    pub text: String,
}

/// What `CSS.setContainerQueryConditionText` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetContainerQueryConditionTextReturns {
    /// The resulting CSS container query rule after modification.
    #[serde(rename = "containerQuery")]
    pub container_query: CssContainerQuery,
}

impl crate::typed::Command for SetContainerQueryConditionTextParams {
    const METHOD: &'static str = "CSS.setContainerQueryConditionText";
    type Returns = SetContainerQueryConditionTextReturns;
}

/// Modifies the expression of a supports at-rule.
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.setSupportsText`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetSupportsTextParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    pub range: SourceRange,
    pub text: String,
}

/// What `CSS.setSupportsText` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetSupportsTextReturns {
    /// The resulting CSS Supports rule after modification.
    pub supports: CssSupports,
}

impl crate::typed::Command for SetSupportsTextParams {
    const METHOD: &'static str = "CSS.setSupportsText";
    type Returns = SetSupportsTextReturns;
}

/// Modifies the expression of a navigation at-rule.
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.setNavigationText`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetNavigationTextParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    pub range: SourceRange,
    pub text: String,
}

/// What `CSS.setNavigationText` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetNavigationTextReturns {
    /// The resulting CSS Navigation rule after modification.
    pub navigation: CssNavigation,
}

impl crate::typed::Command for SetNavigationTextParams {
    const METHOD: &'static str = "CSS.setNavigationText";
    type Returns = SetNavigationTextReturns;
}

/// Modifies the expression of a scope at-rule.
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.setScopeText`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetScopeTextParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    pub range: SourceRange,
    pub text: String,
}

/// What `CSS.setScopeText` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetScopeTextReturns {
    /// The resulting CSS Scope rule after modification.
    pub scope: CssScope,
}

impl crate::typed::Command for SetScopeTextParams {
    const METHOD: &'static str = "CSS.setScopeText";
    type Returns = SetScopeTextReturns;
}

/// Modifies the rule selector.
///
/// Parameters of `CSS.setRuleSelector`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetRuleSelectorParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    pub range: SourceRange,
    pub selector: String,
}

/// What `CSS.setRuleSelector` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetRuleSelectorReturns {
    /// The resulting selector list after modification.
    #[serde(rename = "selectorList")]
    pub selector_list: SelectorList,
}

impl crate::typed::Command for SetRuleSelectorParams {
    const METHOD: &'static str = "CSS.setRuleSelector";
    type Returns = SetRuleSelectorReturns;
}

/// Sets the new stylesheet text.
///
/// Parameters of `CSS.setStyleSheetText`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetStyleSheetTextParams {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
    pub text: String,
}

/// What `CSS.setStyleSheetText` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetStyleSheetTextReturns {
    /// URL of source map associated with script (if any).
    #[serde(
        rename = "sourceMapURL",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_map_url: Option<String>,
}

impl crate::typed::Command for SetStyleSheetTextParams {
    const METHOD: &'static str = "CSS.setStyleSheetText";
    type Returns = SetStyleSheetTextReturns;
}

/// Applies specified style edits one after another in the given order.
///
/// Parameters of `CSS.setStyleTexts`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetStyleTextsParams {
    pub edits: Vec<StyleDeclarationEdit>,
    /// NodeId for the DOM node in whose context custom property declarations for
    /// registered properties should be validated. If omitted, declarations in the
    /// new rule text can only be validated statically, which may produce
    /// incorrect results if the declaration contains a var() for example.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "nodeForPropertySyntaxValidation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub node_for_property_syntax_validation: Option<crate::protocol::dom::NodeId>,
}

/// What `CSS.setStyleTexts` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetStyleTextsReturns {
    /// The resulting styles after modification.
    pub styles: Vec<CssStyle>,
}

impl crate::typed::Command for SetStyleTextsParams {
    const METHOD: &'static str = "CSS.setStyleTexts";
    type Returns = SetStyleTextsReturns;
}

/// Enables the selector recording.
///
/// Parameters of `CSS.startRuleUsageTracking`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StartRuleUsageTrackingParams {}

impl crate::typed::Command for StartRuleUsageTrackingParams {
    const METHOD: &'static str = "CSS.startRuleUsageTracking";
    type Returns = crate::typed::NoReturns;
}

/// Stop tracking rule usage and return the list of rules that were used since
/// last call to `takeCoverageDelta` (or since start of coverage
/// instrumentation).
///
/// Parameters of `CSS.stopRuleUsageTracking`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StopRuleUsageTrackingParams {}

/// What `CSS.stopRuleUsageTracking` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StopRuleUsageTrackingReturns {
    #[serde(rename = "ruleUsage")]
    pub rule_usage: Vec<RuleUsage>,
}

impl crate::typed::Command for StopRuleUsageTrackingParams {
    const METHOD: &'static str = "CSS.stopRuleUsageTracking";
    type Returns = StopRuleUsageTrackingReturns;
}

/// Obtain list of rules that became used since last call to this method (or
/// since start of coverage instrumentation).
///
/// Parameters of `CSS.takeCoverageDelta`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TakeCoverageDeltaParams {}

/// What `CSS.takeCoverageDelta` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TakeCoverageDeltaReturns {
    pub coverage: Vec<RuleUsage>,
    /// Monotonically increasing time, in seconds.
    pub timestamp: f64,
}

impl crate::typed::Command for TakeCoverageDeltaParams {
    const METHOD: &'static str = "CSS.takeCoverageDelta";
    type Returns = TakeCoverageDeltaReturns;
}

/// Enables/disables rendering of local CSS fonts (enabled by default).
///
/// Experimental: may change without notice.
///
/// Parameters of `CSS.setLocalFontsEnabled`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetLocalFontsEnabledParams {
    /// Whether rendering of local fonts is enabled.
    pub enabled: bool,
}

impl crate::typed::Command for SetLocalFontsEnabledParams {
    const METHOD: &'static str = "CSS.setLocalFontsEnabled";
    type Returns = crate::typed::NoReturns;
}

/// Fires whenever a web font is updated. A non-empty font parameter indicates
/// a successfully loaded web font.
///
/// Payload of the `CSS.fontsUpdated` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FontsUpdatedEvent {
    /// The web font that has loaded.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub font: Option<FontFace>,
}

impl crate::typed::Event for FontsUpdatedEvent {
    const METHOD: &'static str = "CSS.fontsUpdated";
}

/// Fires whenever a MediaQuery result changes (for example, after a browser
/// window has been resized.) The current implementation considers only
/// viewport-dependent media features.
///
/// Payload of the `CSS.mediaQueryResultChanged` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MediaQueryResultChangedEvent {}

impl crate::typed::Event for MediaQueryResultChangedEvent {
    const METHOD: &'static str = "CSS.mediaQueryResultChanged";
}

/// Fired whenever an active document stylesheet is added.
///
/// Payload of the `CSS.styleSheetAdded` event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StyleSheetAddedEvent {
    /// Added stylesheet metainfo.
    pub header: CssStyleSheetHeader,
}

impl crate::typed::Event for StyleSheetAddedEvent {
    const METHOD: &'static str = "CSS.styleSheetAdded";
}

/// Fired whenever a stylesheet is changed as a result of the client
/// operation.
///
/// Payload of the `CSS.styleSheetChanged` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StyleSheetChangedEvent {
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
}

impl crate::typed::Event for StyleSheetChangedEvent {
    const METHOD: &'static str = "CSS.styleSheetChanged";
}

/// Fired whenever an active document stylesheet is removed.
///
/// Payload of the `CSS.styleSheetRemoved` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StyleSheetRemovedEvent {
    /// Identifier of the removed stylesheet.
    #[serde(rename = "styleSheetId")]
    pub style_sheet_id: crate::protocol::dom::StyleSheetId,
}

impl crate::typed::Event for StyleSheetRemovedEvent {
    const METHOD: &'static str = "CSS.styleSheetRemoved";
}

/// Experimental: may change without notice.
///
/// Payload of the `CSS.computedStyleUpdated` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ComputedStyleUpdatedEvent {
    /// The node id that has updated computed styles.
    #[serde(rename = "nodeId")]
    pub node_id: crate::protocol::dom::NodeId,
}

impl crate::typed::Event for ComputedStyleUpdatedEvent {
    const METHOD: &'static str = "CSS.computedStyleUpdated";
}
