// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! The `DeviceAccess` domain.
//!
//! Types, command parameters and event payloads for the `DeviceAccess`
//! domain. The method-name constants for the same domain are in
//! [`crate::methods`].
//!
//! This domain is experimental and may change without notice.

use serde::{Deserialize, Serialize};

/// Device request id.
pub type RequestId = String;

/// A device id.
pub type DeviceId = String;

/// Device information displayed in a user prompt to select a device.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PromptDevice {
    pub id: DeviceId,
    /// Display name as it appears in a device request user prompt.
    pub name: String,
}

/// Enable events in this domain.
///
/// Parameters of `DeviceAccess.enable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnableParams {}

impl crate::typed::Command for EnableParams {
    const METHOD: &'static str = "DeviceAccess.enable";
    type Returns = crate::typed::NoReturns;
}

/// Disable events in this domain.
///
/// Parameters of `DeviceAccess.disable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DisableParams {}

impl crate::typed::Command for DisableParams {
    const METHOD: &'static str = "DeviceAccess.disable";
    type Returns = crate::typed::NoReturns;
}

/// Select a device in response to a DeviceAccess.deviceRequestPrompted event.
///
/// Parameters of `DeviceAccess.selectPrompt`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SelectPromptParams {
    pub id: RequestId,
    #[serde(rename = "deviceId")]
    pub device_id: DeviceId,
}

impl crate::typed::Command for SelectPromptParams {
    const METHOD: &'static str = "DeviceAccess.selectPrompt";
    type Returns = crate::typed::NoReturns;
}

/// Cancel a prompt in response to a DeviceAccess.deviceRequestPrompted event.
///
/// Parameters of `DeviceAccess.cancelPrompt`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CancelPromptParams {
    pub id: RequestId,
}

impl crate::typed::Command for CancelPromptParams {
    const METHOD: &'static str = "DeviceAccess.cancelPrompt";
    type Returns = crate::typed::NoReturns;
}

/// A device request opened a user prompt to select a device. Respond with the
/// selectPrompt or cancelPrompt command.
///
/// Payload of the `DeviceAccess.deviceRequestPrompted` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DeviceRequestPromptedEvent {
    pub id: RequestId,
    pub devices: Vec<PromptDevice>,
}

impl crate::typed::Event for DeviceRequestPromptedEvent {
    const METHOD: &'static str = "DeviceAccess.deviceRequestPrompted";
}
