// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! This domain emulates different environments for the page.
//!
//! Types, command parameters and event payloads for the `Emulation`
//! domain. The method-name constants for the same domain are in
//! [`crate::methods`].

use serde::{Deserialize, Serialize};

/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SafeAreaInsets {
    /// Overrides safe-area-inset-top.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top: Option<i64>,
    /// Overrides safe-area-max-inset-top.
    #[serde(rename = "topMax", default, skip_serializing_if = "Option::is_none")]
    pub top_max: Option<i64>,
    /// Overrides safe-area-inset-left.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub left: Option<i64>,
    /// Overrides safe-area-max-inset-left.
    #[serde(rename = "leftMax", default, skip_serializing_if = "Option::is_none")]
    pub left_max: Option<i64>,
    /// Overrides safe-area-inset-bottom.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bottom: Option<i64>,
    /// Overrides safe-area-max-inset-bottom.
    #[serde(rename = "bottomMax", default, skip_serializing_if = "Option::is_none")]
    pub bottom_max: Option<i64>,
    /// Overrides safe-area-inset-right.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub right: Option<i64>,
    /// Overrides safe-area-max-inset-right.
    #[serde(rename = "rightMax", default, skip_serializing_if = "Option::is_none")]
    pub right_max: Option<i64>,
}

/// Screen orientation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ScreenOrientation {
    /// Orientation type.
    pub r#type: ScreenOrientationType,
    /// Orientation angle.
    pub angle: i64,
}

/// The values `type` accepts on `ScreenOrientation`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ScreenOrientationType {
    /// `portraitPrimary`
    #[serde(rename = "portraitPrimary")]
    PortraitPrimary,
    /// `portraitSecondary`
    #[serde(rename = "portraitSecondary")]
    PortraitSecondary,
    /// `landscapePrimary`
    #[serde(rename = "landscapePrimary")]
    LandscapePrimary,
    /// `landscapeSecondary`
    #[serde(rename = "landscapeSecondary")]
    LandscapeSecondary,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DisplayFeature {
    /// Orientation of a display feature in relation to screen
    pub orientation: DisplayFeatureOrientation,
    /// The offset from the screen origin in either the x (for vertical
    /// orientation) or y (for horizontal orientation) direction.
    pub offset: i64,
    /// A display feature may mask content such that it is not physically
    /// displayed - this length along with the offset describes this area. A
    /// display feature that only splits content will have a 0 mask_length.
    #[serde(rename = "maskLength")]
    pub mask_length: i64,
}

/// The values `orientation` accepts on `DisplayFeature`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DisplayFeatureOrientation {
    /// `vertical`
    #[serde(rename = "vertical")]
    Vertical,
    /// `horizontal`
    #[serde(rename = "horizontal")]
    Horizontal,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DevicePosture {
    /// Current posture of the device
    pub r#type: DevicePostureType,
}

/// The values `type` accepts on `DevicePosture`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DevicePostureType {
    /// `continuous`
    #[serde(rename = "continuous")]
    Continuous,
    /// `folded`
    #[serde(rename = "folded")]
    Folded,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MediaFeature {
    pub name: String,
    pub value: String,
}

/// advance: If the scheduler runs out of immediate work, the virtual time
/// base may fast forward to allow the next delayed task (if any) to run;
/// pause: The virtual time base may not advance;
/// pauseIfNetworkFetchesPending: The virtual time base may not advance if
/// there are any pending resource fetches.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum VirtualTimePolicy {
    /// `advance`
    #[serde(rename = "advance")]
    Advance,
    /// `pause`
    #[serde(rename = "pause")]
    Pause,
    /// `pauseIfNetworkFetchesPending`
    #[serde(rename = "pauseIfNetworkFetchesPending")]
    PauseIfNetworkFetchesPending,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Used to specify User Agent Client Hints to emulate. See
/// <https://wicg.github.io/ua-client-hints>
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UserAgentBrandVersion {
    pub brand: String,
    pub version: String,
}

/// Used to specify User Agent Client Hints to emulate. See
/// <https://wicg.github.io/ua-client-hints> Missing optional values will be
/// filled in by the target with what it would normally use.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UserAgentMetadata {
    /// Brands appearing in Sec-CH-UA.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub brands: Option<Vec<UserAgentBrandVersion>>,
    /// Brands appearing in Sec-CH-UA-Full-Version-List.
    #[serde(
        rename = "fullVersionList",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub full_version_list: Option<Vec<UserAgentBrandVersion>>,
    /// Deprecated in the protocol.
    #[serde(
        rename = "fullVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub full_version: Option<String>,
    pub platform: String,
    #[serde(rename = "platformVersion")]
    pub platform_version: String,
    pub architecture: String,
    pub model: String,
    pub mobile: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bitness: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wow64: Option<bool>,
    /// Used to specify User Agent form-factor values. See
    /// <https://wicg.github.io/ua-client-hints/#sec-ch-ua-form-factors>
    #[serde(
        rename = "formFactors",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub form_factors: Option<Vec<String>>,
}

/// Used to specify sensor types to emulate. See
/// <https://w3c.github.io/sensors/#automation> for more information.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SensorType {
    /// `absolute-orientation`
    #[serde(rename = "absolute-orientation")]
    AbsoluteOrientation,
    /// `accelerometer`
    #[serde(rename = "accelerometer")]
    Accelerometer,
    /// `ambient-light`
    #[serde(rename = "ambient-light")]
    AmbientLight,
    /// `gravity`
    #[serde(rename = "gravity")]
    Gravity,
    /// `gyroscope`
    #[serde(rename = "gyroscope")]
    Gyroscope,
    /// `linear-acceleration`
    #[serde(rename = "linear-acceleration")]
    LinearAcceleration,
    /// `magnetometer`
    #[serde(rename = "magnetometer")]
    Magnetometer,
    /// `relative-orientation`
    #[serde(rename = "relative-orientation")]
    RelativeOrientation,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SensorMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub available: Option<bool>,
    #[serde(
        rename = "minimumFrequency",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub minimum_frequency: Option<f64>,
    #[serde(
        rename = "maximumFrequency",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub maximum_frequency: Option<f64>,
}

/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SensorReadingSingle {
    pub value: f64,
}

/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SensorReadingXyz {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SensorReadingQuaternion {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub w: f64,
}

/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SensorReading {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub single: Option<SensorReadingSingle>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub xyz: Option<SensorReadingXyz>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quaternion: Option<SensorReadingQuaternion>,
}

/// Experimental: may change without notice.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PressureSource {
    /// `cpu`
    #[serde(rename = "cpu")]
    Cpu,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Experimental: may change without notice.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PressureState {
    /// `nominal`
    #[serde(rename = "nominal")]
    Nominal,
    /// `fair`
    #[serde(rename = "fair")]
    Fair,
    /// `serious`
    #[serde(rename = "serious")]
    Serious,
    /// `critical`
    #[serde(rename = "critical")]
    Critical,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PressureMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub available: Option<bool>,
}

/// Experimental: may change without notice.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkAreaInsets {
    /// Work area top inset in pixels. Default is 0;
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top: Option<i64>,
    /// Work area left inset in pixels. Default is 0;
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub left: Option<i64>,
    /// Work area bottom inset in pixels. Default is 0;
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bottom: Option<i64>,
    /// Work area right inset in pixels. Default is 0;
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub right: Option<i64>,
}

/// Experimental: may change without notice.
pub type ScreenId = String;

/// Screen information similar to the one returned by
/// window.getScreenDetails() method, see
/// <https://w3c.github.io/window-management/#screendetailed>.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ScreenInfo {
    /// Offset of the left edge of the screen.
    pub left: i64,
    /// Offset of the top edge of the screen.
    pub top: i64,
    /// Width of the screen.
    pub width: i64,
    /// Height of the screen.
    pub height: i64,
    /// Offset of the left edge of the available screen area.
    #[serde(rename = "availLeft")]
    pub avail_left: i64,
    /// Offset of the top edge of the available screen area.
    #[serde(rename = "availTop")]
    pub avail_top: i64,
    /// Width of the available screen area.
    #[serde(rename = "availWidth")]
    pub avail_width: i64,
    /// Height of the available screen area.
    #[serde(rename = "availHeight")]
    pub avail_height: i64,
    /// Specifies the screen's device pixel ratio.
    #[serde(rename = "devicePixelRatio")]
    pub device_pixel_ratio: f64,
    /// Specifies the screen's orientation.
    pub orientation: ScreenOrientation,
    /// Specifies the screen's color depth in bits.
    #[serde(rename = "colorDepth")]
    pub color_depth: i64,
    /// Indicates whether the device has multiple screens.
    #[serde(rename = "isExtended")]
    pub is_extended: bool,
    /// Indicates whether the screen is internal to the device or external,
    /// attached to the device.
    #[serde(rename = "isInternal")]
    pub is_internal: bool,
    /// Indicates whether the screen is set as the the operating system primary
    /// screen.
    #[serde(rename = "isPrimary")]
    pub is_primary: bool,
    /// Specifies the descriptive label for the screen.
    pub label: String,
    /// Specifies the unique identifier of the screen.
    pub id: ScreenId,
}

/// Enum of image types that can be disabled.
///
/// Experimental: may change without notice.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DisabledImageType {
    /// `avif`
    #[serde(rename = "avif")]
    Avif,
    /// `jxl`
    #[serde(rename = "jxl")]
    Jxl,
    /// `webp`
    #[serde(rename = "webp")]
    Webp,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Tells whether emulation is supported.
///
/// Deprecated in the protocol.
///
/// Parameters of `Emulation.canEmulate`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CanEmulateParams {}

/// What `Emulation.canEmulate` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CanEmulateReturns {
    /// True if emulation is supported.
    pub result: bool,
}

impl crate::typed::Command for CanEmulateParams {
    const METHOD: &'static str = "Emulation.canEmulate";
    type Returns = CanEmulateReturns;
}

/// Clears the overridden device metrics.
///
/// Parameters of `Emulation.clearDeviceMetricsOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ClearDeviceMetricsOverrideParams {}

impl crate::typed::Command for ClearDeviceMetricsOverrideParams {
    const METHOD: &'static str = "Emulation.clearDeviceMetricsOverride";
    type Returns = crate::typed::NoReturns;
}

/// Clears the overridden Geolocation Position and Error.
///
/// Parameters of `Emulation.clearGeolocationOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ClearGeolocationOverrideParams {}

impl crate::typed::Command for ClearGeolocationOverrideParams {
    const METHOD: &'static str = "Emulation.clearGeolocationOverride";
    type Returns = crate::typed::NoReturns;
}

/// Requests that page scale factor is reset to initial values.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.resetPageScaleFactor`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ResetPageScaleFactorParams {}

impl crate::typed::Command for ResetPageScaleFactorParams {
    const METHOD: &'static str = "Emulation.resetPageScaleFactor";
    type Returns = crate::typed::NoReturns;
}

/// Enables or disables simulating a focused and active page.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setFocusEmulationEnabled`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetFocusEmulationEnabledParams {
    /// Whether to enable to disable focus emulation.
    pub enabled: bool,
}

impl crate::typed::Command for SetFocusEmulationEnabledParams {
    const METHOD: &'static str = "Emulation.setFocusEmulationEnabled";
    type Returns = crate::typed::NoReturns;
}

/// Automatically render all web contents using a dark theme.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setAutoDarkModeOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetAutoDarkModeOverrideParams {
    /// Whether to enable or disable automatic dark mode. If not specified, any
    /// existing override will be cleared.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl crate::typed::Command for SetAutoDarkModeOverrideParams {
    const METHOD: &'static str = "Emulation.setAutoDarkModeOverride";
    type Returns = crate::typed::NoReturns;
}

/// Enables CPU throttling to emulate slow CPUs.
///
/// Parameters of `Emulation.setCPUThrottlingRate`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetCpuThrottlingRateParams {
    /// Throttling rate as a slowdown factor (1 is no throttle, 2 is 2x slowdown,
    /// etc).
    pub rate: f64,
}

impl crate::typed::Command for SetCpuThrottlingRateParams {
    const METHOD: &'static str = "Emulation.setCPUThrottlingRate";
    type Returns = crate::typed::NoReturns;
}

/// Sets or clears an override of the default background color of the frame.
/// This override is used if the content does not specify one.
///
/// Parameters of `Emulation.setDefaultBackgroundColorOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetDefaultBackgroundColorOverrideParams {
    /// RGBA of the default background color. If not specified, any existing
    /// override will be cleared.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<crate::protocol::dom::Rgba>,
}

impl crate::typed::Command for SetDefaultBackgroundColorOverrideParams {
    const METHOD: &'static str = "Emulation.setDefaultBackgroundColorOverride";
    type Returns = crate::typed::NoReturns;
}

/// Overrides the values for env(safe-area-inset-*) and
/// env(safe-area-max-inset-*). Unset values will cause the respective
/// variables to be undefined, even if previously overridden.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setSafeAreaInsetsOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetSafeAreaInsetsOverrideParams {
    pub insets: SafeAreaInsets,
}

impl crate::typed::Command for SetSafeAreaInsetsOverrideParams {
    const METHOD: &'static str = "Emulation.setSafeAreaInsetsOverride";
    type Returns = crate::typed::NoReturns;
}

/// Overrides the values of device screen dimensions (window.screen.width,
/// window.screen.height, window.innerWidth, window.innerHeight, and
/// "device-width"/"device-height"-related CSS media query results).
///
/// Parameters of `Emulation.setDeviceMetricsOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetDeviceMetricsOverrideParams {
    /// Overriding width value in pixels (minimum 0, maximum 10000000). 0 disables
    /// the override.
    pub width: i64,
    /// Overriding height value in pixels (minimum 0, maximum 10000000). 0
    /// disables the override.
    pub height: i64,
    /// Overriding device scale factor value. 0 disables the override.
    #[serde(rename = "deviceScaleFactor")]
    pub device_scale_factor: f64,
    /// Whether to emulate mobile device. This includes viewport meta tag, overlay
    /// scrollbars, text autosizing and more.
    pub mobile: bool,
    /// Scale to apply to resulting view image.
    ///
    /// Experimental: may change without notice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,
    /// Overriding screen width value in pixels (minimum 0, maximum 10000000).
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "screenWidth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub screen_width: Option<i64>,
    /// Overriding screen height value in pixels (minimum 0, maximum 10000000).
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "screenHeight",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub screen_height: Option<i64>,
    /// Overriding view X position on screen in pixels (minimum 0, maximum
    /// 10000000).
    ///
    /// Experimental: may change without notice.
    #[serde(rename = "positionX", default, skip_serializing_if = "Option::is_none")]
    pub position_x: Option<i64>,
    /// Overriding view Y position on screen in pixels (minimum 0, maximum
    /// 10000000).
    ///
    /// Experimental: may change without notice.
    #[serde(rename = "positionY", default, skip_serializing_if = "Option::is_none")]
    pub position_y: Option<i64>,
    /// Do not set visible view size, rely upon explicit setVisibleSize call.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "dontSetVisibleSize",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dont_set_visible_size: Option<bool>,
    /// Screen orientation override.
    #[serde(
        rename = "screenOrientation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub screen_orientation: Option<ScreenOrientation>,
    /// If set, the visible area of the page will be overridden to this viewport.
    /// This viewport change is not observed by the page, e.g. viewport-relative
    /// elements do not change positions.
    ///
    /// Experimental: may change without notice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewport: Option<crate::protocol::page::Viewport>,
    /// If set, the display feature of a multi-segment screen. If not set,
    /// multi-segment support is turned-off. Deprecated, use
    /// Emulation.setDisplayFeaturesOverride.
    ///
    /// Deprecated in the protocol.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "displayFeature",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub display_feature: Option<DisplayFeature>,
    /// If set, the posture of a foldable device. If not set the posture is set to
    /// continuous. Deprecated, use Emulation.setDevicePostureOverride.
    ///
    /// Deprecated in the protocol.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "devicePosture",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub device_posture: Option<DevicePosture>,
    /// Scrollbar type. Default: `default`.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "scrollbarType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scrollbar_type: Option<SetDeviceMetricsOverrideScrollbarType>,
    /// If set to true, enables screen orientation lock emulation, which
    /// intercepts screen.orientation.lock() calls from the page and reports
    /// orientation changes via screenOrientationLockChanged events. This is
    /// useful for emulating mobile device orientation lock behavior in responsive
    /// design mode.
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "screenOrientationLockEmulation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub screen_orientation_lock_emulation: Option<bool>,
}

/// The values `scrollbarType` accepts on `setDeviceMetricsOverride`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SetDeviceMetricsOverrideScrollbarType {
    /// `overlay`
    #[serde(rename = "overlay")]
    Overlay,
    /// `default`
    #[serde(rename = "default")]
    Default,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

impl crate::typed::Command for SetDeviceMetricsOverrideParams {
    const METHOD: &'static str = "Emulation.setDeviceMetricsOverride";
    type Returns = crate::typed::NoReturns;
}

/// Start reporting the given posture value to the Device Posture API. This
/// override can also be set in setDeviceMetricsOverride().
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setDevicePostureOverride`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetDevicePostureOverrideParams {
    pub posture: DevicePosture,
}

impl crate::typed::Command for SetDevicePostureOverrideParams {
    const METHOD: &'static str = "Emulation.setDevicePostureOverride";
    type Returns = crate::typed::NoReturns;
}

/// Clears a device posture override set with either
/// setDeviceMetricsOverride() or setDevicePostureOverride() and starts using
/// posture information from the platform again. Does nothing if no override
/// is set.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.clearDevicePostureOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ClearDevicePostureOverrideParams {}

impl crate::typed::Command for ClearDevicePostureOverrideParams {
    const METHOD: &'static str = "Emulation.clearDevicePostureOverride";
    type Returns = crate::typed::NoReturns;
}

/// Start using the given display features to pupulate the Viewport Segments
/// API. This override can also be set in setDeviceMetricsOverride().
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setDisplayFeaturesOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetDisplayFeaturesOverrideParams {
    pub features: Vec<DisplayFeature>,
}

impl crate::typed::Command for SetDisplayFeaturesOverrideParams {
    const METHOD: &'static str = "Emulation.setDisplayFeaturesOverride";
    type Returns = crate::typed::NoReturns;
}

/// Clears the display features override set with either
/// setDeviceMetricsOverride() or setDisplayFeaturesOverride() and starts
/// using display features from the platform again. Does nothing if no
/// override is set.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.clearDisplayFeaturesOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ClearDisplayFeaturesOverrideParams {}

impl crate::typed::Command for ClearDisplayFeaturesOverrideParams {
    const METHOD: &'static str = "Emulation.clearDisplayFeaturesOverride";
    type Returns = crate::typed::NoReturns;
}

/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setScrollbarsHidden`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetScrollbarsHiddenParams {
    /// Whether scrollbars should be always hidden.
    pub hidden: bool,
}

impl crate::typed::Command for SetScrollbarsHiddenParams {
    const METHOD: &'static str = "Emulation.setScrollbarsHidden";
    type Returns = crate::typed::NoReturns;
}

/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setDocumentCookieDisabled`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetDocumentCookieDisabledParams {
    /// Whether document.coookie API should be disabled.
    pub disabled: bool,
}

impl crate::typed::Command for SetDocumentCookieDisabledParams {
    const METHOD: &'static str = "Emulation.setDocumentCookieDisabled";
    type Returns = crate::typed::NoReturns;
}

/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setEmitTouchEventsForMouse`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetEmitTouchEventsForMouseParams {
    /// Whether touch emulation based on mouse input should be enabled.
    pub enabled: bool,
    /// Touch/gesture events configuration. Default: current platform.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub configuration: Option<SetEmitTouchEventsForMouseConfiguration>,
}

/// The values `configuration` accepts on `setEmitTouchEventsForMouse`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SetEmitTouchEventsForMouseConfiguration {
    /// `mobile`
    #[serde(rename = "mobile")]
    Mobile,
    /// `desktop`
    #[serde(rename = "desktop")]
    Desktop,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

impl crate::typed::Command for SetEmitTouchEventsForMouseParams {
    const METHOD: &'static str = "Emulation.setEmitTouchEventsForMouse";
    type Returns = crate::typed::NoReturns;
}

/// Emulates the given media type or media feature for CSS media queries.
///
/// Parameters of `Emulation.setEmulatedMedia`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetEmulatedMediaParams {
    /// Media type to emulate. Empty string disables the override.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media: Option<String>,
    /// Media features to emulate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<MediaFeature>>,
}

impl crate::typed::Command for SetEmulatedMediaParams {
    const METHOD: &'static str = "Emulation.setEmulatedMedia";
    type Returns = crate::typed::NoReturns;
}

/// Emulates the given vision deficiency.
///
/// Parameters of `Emulation.setEmulatedVisionDeficiency`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetEmulatedVisionDeficiencyParams {
    /// Vision deficiency to emulate. Order: best-effort emulations come first,
    /// followed by any physiologically accurate emulations for medically
    /// recognized color vision deficiencies.
    pub r#type: SetEmulatedVisionDeficiencyType,
}

/// The values `type` accepts on `setEmulatedVisionDeficiency`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SetEmulatedVisionDeficiencyType {
    /// `none`
    #[serde(rename = "none")]
    None,
    /// `blurredVision`
    #[serde(rename = "blurredVision")]
    BlurredVision,
    /// `reducedContrast`
    #[serde(rename = "reducedContrast")]
    ReducedContrast,
    /// `achromatopsia`
    #[serde(rename = "achromatopsia")]
    Achromatopsia,
    /// `deuteranopia`
    #[serde(rename = "deuteranopia")]
    Deuteranopia,
    /// `protanopia`
    #[serde(rename = "protanopia")]
    Protanopia,
    /// `tritanopia`
    #[serde(rename = "tritanopia")]
    Tritanopia,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

impl crate::typed::Command for SetEmulatedVisionDeficiencyParams {
    const METHOD: &'static str = "Emulation.setEmulatedVisionDeficiency";
    type Returns = crate::typed::NoReturns;
}

/// Emulates the given OS text scale.
///
/// Parameters of `Emulation.setEmulatedOSTextScale`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetEmulatedOsTextScaleParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,
}

impl crate::typed::Command for SetEmulatedOsTextScaleParams {
    const METHOD: &'static str = "Emulation.setEmulatedOSTextScale";
    type Returns = crate::typed::NoReturns;
}

/// Overrides the Geolocation Position or Error. Omitting latitude, longitude
/// or accuracy emulates position unavailable.
///
/// Parameters of `Emulation.setGeolocationOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetGeolocationOverrideParams {
    /// Mock latitude
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// Mock longitude
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    /// Mock accuracy
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub accuracy: Option<f64>,
    /// Mock altitude
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub altitude: Option<f64>,
    /// Mock altitudeAccuracy
    #[serde(
        rename = "altitudeAccuracy",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub altitude_accuracy: Option<f64>,
    /// Mock heading
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub heading: Option<f64>,
    /// Mock speed
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speed: Option<f64>,
}

impl crate::typed::Command for SetGeolocationOverrideParams {
    const METHOD: &'static str = "Emulation.setGeolocationOverride";
    type Returns = crate::typed::NoReturns;
}

/// Experimental: may change without notice.
///
/// Parameters of `Emulation.getOverriddenSensorInformation`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetOverriddenSensorInformationParams {
    pub r#type: SensorType,
}

/// What `Emulation.getOverriddenSensorInformation` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetOverriddenSensorInformationReturns {
    #[serde(rename = "requestedSamplingFrequency")]
    pub requested_sampling_frequency: f64,
}

impl crate::typed::Command for GetOverriddenSensorInformationParams {
    const METHOD: &'static str = "Emulation.getOverriddenSensorInformation";
    type Returns = GetOverriddenSensorInformationReturns;
}

/// Overrides a platform sensor of a given type. If |enabled| is true, calls
/// to Sensor.start() will use a virtual sensor as backend rather than
/// fetching data from a real hardware sensor. Otherwise, existing virtual
/// sensor-backend Sensor objects will fire an error event and new calls to
/// Sensor.start() will attempt to use a real sensor instead.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setSensorOverrideEnabled`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetSensorOverrideEnabledParams {
    pub enabled: bool,
    pub r#type: SensorType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<SensorMetadata>,
}

impl crate::typed::Command for SetSensorOverrideEnabledParams {
    const METHOD: &'static str = "Emulation.setSensorOverrideEnabled";
    type Returns = crate::typed::NoReturns;
}

/// Updates the sensor readings reported by a sensor type previously
/// overridden by setSensorOverrideEnabled.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setSensorOverrideReadings`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetSensorOverrideReadingsParams {
    pub r#type: SensorType,
    pub reading: SensorReading,
}

impl crate::typed::Command for SetSensorOverrideReadingsParams {
    const METHOD: &'static str = "Emulation.setSensorOverrideReadings";
    type Returns = crate::typed::NoReturns;
}

/// Overrides a pressure source of a given type, as used by the Compute
/// Pressure API, so that updates to PressureObserver.observe() are provided
/// via setPressureStateOverride instead of being retrieved from
/// platform-provided telemetry data.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setPressureSourceOverrideEnabled`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetPressureSourceOverrideEnabledParams {
    pub enabled: bool,
    pub source: PressureSource,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<PressureMetadata>,
}

impl crate::typed::Command for SetPressureSourceOverrideEnabledParams {
    const METHOD: &'static str = "Emulation.setPressureSourceOverrideEnabled";
    type Returns = crate::typed::NoReturns;
}

/// Provides a given pressure state that will be processed and eventually be
/// delivered to PressureObserver users. |source| must have been previously
/// overridden by setPressureSourceOverrideEnabled.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setPressureStateOverride`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetPressureStateOverrideParams {
    pub source: PressureSource,
    pub state: PressureState,
}

impl crate::typed::Command for SetPressureStateOverrideParams {
    const METHOD: &'static str = "Emulation.setPressureStateOverride";
    type Returns = crate::typed::NoReturns;
}

/// Overrides the Idle state.
///
/// Parameters of `Emulation.setIdleOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetIdleOverrideParams {
    /// Mock isUserActive
    #[serde(rename = "isUserActive")]
    pub is_user_active: bool,
    /// Mock isScreenUnlocked
    #[serde(rename = "isScreenUnlocked")]
    pub is_screen_unlocked: bool,
}

impl crate::typed::Command for SetIdleOverrideParams {
    const METHOD: &'static str = "Emulation.setIdleOverride";
    type Returns = crate::typed::NoReturns;
}

/// Clears Idle state overrides.
///
/// Parameters of `Emulation.clearIdleOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ClearIdleOverrideParams {}

impl crate::typed::Command for ClearIdleOverrideParams {
    const METHOD: &'static str = "Emulation.clearIdleOverride";
    type Returns = crate::typed::NoReturns;
}

/// Overrides value returned by the javascript navigator object.
///
/// Deprecated in the protocol.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setNavigatorOverrides`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetNavigatorOverridesParams {
    /// The platform navigator.platform should return.
    pub platform: String,
}

impl crate::typed::Command for SetNavigatorOverridesParams {
    const METHOD: &'static str = "Emulation.setNavigatorOverrides";
    type Returns = crate::typed::NoReturns;
}

/// Sets a specified page scale factor.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setPageScaleFactor`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetPageScaleFactorParams {
    /// Page scale factor.
    #[serde(rename = "pageScaleFactor")]
    pub page_scale_factor: f64,
}

impl crate::typed::Command for SetPageScaleFactorParams {
    const METHOD: &'static str = "Emulation.setPageScaleFactor";
    type Returns = crate::typed::NoReturns;
}

/// Switches script execution in the page.
///
/// Parameters of `Emulation.setScriptExecutionDisabled`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetScriptExecutionDisabledParams {
    /// Whether script execution should be disabled in the page.
    pub value: bool,
}

impl crate::typed::Command for SetScriptExecutionDisabledParams {
    const METHOD: &'static str = "Emulation.setScriptExecutionDisabled";
    type Returns = crate::typed::NoReturns;
}

/// Enables touch on platforms which do not support them.
///
/// Parameters of `Emulation.setTouchEmulationEnabled`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetTouchEmulationEnabledParams {
    /// Whether the touch event emulation should be enabled.
    pub enabled: bool,
    /// Maximum touch points supported. Defaults to one.
    #[serde(
        rename = "maxTouchPoints",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_touch_points: Option<i64>,
}

impl crate::typed::Command for SetTouchEmulationEnabledParams {
    const METHOD: &'static str = "Emulation.setTouchEmulationEnabled";
    type Returns = crate::typed::NoReturns;
}

/// Turns on virtual time for all frames (replacing real-time with a synthetic
/// time source) and sets the current virtual time policy. Note this
/// supersedes any previous time budget.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setVirtualTimePolicy`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetVirtualTimePolicyParams {
    pub policy: VirtualTimePolicy,
    /// If set, after this many virtual milliseconds have elapsed virtual time
    /// will be paused and a virtualTimeBudgetExpired event is sent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub budget: Option<f64>,
    /// If set this specifies the maximum number of tasks that can be run before
    /// virtual is forced forwards to prevent deadlock.
    #[serde(
        rename = "maxVirtualTimeTaskStarvationCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_virtual_time_task_starvation_count: Option<i64>,
    /// If set, base::Time::Now will be overridden to initially return this value.
    #[serde(
        rename = "initialVirtualTime",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub initial_virtual_time: Option<crate::protocol::network::TimeSinceEpoch>,
}

/// What `Emulation.setVirtualTimePolicy` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetVirtualTimePolicyReturns {
    /// Absolute timestamp at which virtual time was first enabled (up time in
    /// milliseconds).
    #[serde(rename = "virtualTimeTicksBase")]
    pub virtual_time_ticks_base: f64,
}

impl crate::typed::Command for SetVirtualTimePolicyParams {
    const METHOD: &'static str = "Emulation.setVirtualTimePolicy";
    type Returns = SetVirtualTimePolicyReturns;
}

/// Overrides default host system locale with the specified one.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setLocaleOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetLocaleOverrideParams {
    /// ICU style C locale (e.g. "en_US"). If not specified or empty, disables the
    /// override and restores default host system locale.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
}

impl crate::typed::Command for SetLocaleOverrideParams {
    const METHOD: &'static str = "Emulation.setLocaleOverride";
    type Returns = crate::typed::NoReturns;
}

/// Overrides default host system timezone with the specified one.
///
/// Parameters of `Emulation.setTimezoneOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetTimezoneOverrideParams {
    /// The timezone identifier. List of supported timezones:
    /// <https://source.chromium.org/chromium/chromium/deps/icu.git/+/faee8bc70570192d82d2978a71e2a615788597d1:source/data/misc/metaZones.txt>
    /// If empty, disables the override and restores default host system timezone.
    #[serde(rename = "timezoneId")]
    pub timezone_id: String,
}

impl crate::typed::Command for SetTimezoneOverrideParams {
    const METHOD: &'static str = "Emulation.setTimezoneOverride";
    type Returns = crate::typed::NoReturns;
}

/// Resizes the frame/viewport of the page. Note that this does not affect the
/// frame's container (e.g. browser window). Can be used to produce
/// screenshots of the specified size. Not supported on Android.
///
/// Deprecated in the protocol.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setVisibleSize`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetVisibleSizeParams {
    /// Frame width (DIP).
    pub width: i64,
    /// Frame height (DIP).
    pub height: i64,
}

impl crate::typed::Command for SetVisibleSizeParams {
    const METHOD: &'static str = "Emulation.setVisibleSize";
    type Returns = crate::typed::NoReturns;
}

/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setDisabledImageTypes`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetDisabledImageTypesParams {
    /// Image types to disable.
    #[serde(rename = "imageTypes")]
    pub image_types: Vec<DisabledImageType>,
}

impl crate::typed::Command for SetDisabledImageTypesParams {
    const METHOD: &'static str = "Emulation.setDisabledImageTypes";
    type Returns = crate::typed::NoReturns;
}

/// Override the value of navigator.connection.saveData
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setDataSaverOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetDataSaverOverrideParams {
    /// Override value. Omitting the parameter disables the override.
    #[serde(
        rename = "dataSaverEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub data_saver_enabled: Option<bool>,
}

impl crate::typed::Command for SetDataSaverOverrideParams {
    const METHOD: &'static str = "Emulation.setDataSaverOverride";
    type Returns = crate::typed::NoReturns;
}

/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setHardwareConcurrencyOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetHardwareConcurrencyOverrideParams {
    /// Hardware concurrency to report
    #[serde(rename = "hardwareConcurrency")]
    pub hardware_concurrency: i64,
}

impl crate::typed::Command for SetHardwareConcurrencyOverrideParams {
    const METHOD: &'static str = "Emulation.setHardwareConcurrencyOverride";
    type Returns = crate::typed::NoReturns;
}

/// Allows overriding user agent with the given string. `userAgentMetadata`
/// must be set for Client Hint headers to be sent.
///
/// Parameters of `Emulation.setUserAgentOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetUserAgentOverrideParams {
    /// User agent to use.
    #[serde(rename = "userAgent")]
    pub user_agent: String,
    /// Browser language to emulate.
    #[serde(
        rename = "acceptLanguage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub accept_language: Option<String>,
    /// The platform navigator.platform should return.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    /// To be sent in Sec-CH-UA-* headers and returned in navigator.userAgentData
    ///
    /// Experimental: may change without notice.
    #[serde(
        rename = "userAgentMetadata",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub user_agent_metadata: Option<UserAgentMetadata>,
}

impl crate::typed::Command for SetUserAgentOverrideParams {
    const METHOD: &'static str = "Emulation.setUserAgentOverride";
    type Returns = crate::typed::NoReturns;
}

/// Allows overriding the automation flag.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setAutomationOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetAutomationOverrideParams {
    /// Whether the override should be enabled.
    pub enabled: bool,
}

impl crate::typed::Command for SetAutomationOverrideParams {
    const METHOD: &'static str = "Emulation.setAutomationOverride";
    type Returns = crate::typed::NoReturns;
}

/// Allows overriding the difference between the small and large viewport
/// sizes, which determine the value of the `svh` and `lvh` unit,
/// respectively. Only supported for top-level frames.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setSmallViewportHeightDifferenceOverride`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetSmallViewportHeightDifferenceOverrideParams {
    /// This will cause an element of size 100svh to be `difference` pixels
    /// smaller than an element of size 100lvh.
    pub difference: i64,
}

impl crate::typed::Command for SetSmallViewportHeightDifferenceOverrideParams {
    const METHOD: &'static str = "Emulation.setSmallViewportHeightDifferenceOverride";
    type Returns = crate::typed::NoReturns;
}

/// Returns device's screen configuration. In headful mode, the physical
/// screens configuration is returned, whereas in headless mode, a virtual
/// headless screen configuration is provided instead.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.getScreenInfos`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetScreenInfosParams {}

/// What `Emulation.getScreenInfos` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetScreenInfosReturns {
    #[serde(rename = "screenInfos")]
    pub screen_infos: Vec<ScreenInfo>,
}

impl crate::typed::Command for GetScreenInfosParams {
    const METHOD: &'static str = "Emulation.getScreenInfos";
    type Returns = GetScreenInfosReturns;
}

/// Add a new screen to the device. Only supported in headless mode.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.addScreen`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AddScreenParams {
    /// Offset of the left edge of the screen in pixels.
    pub left: i64,
    /// Offset of the top edge of the screen in pixels.
    pub top: i64,
    /// The width of the screen in pixels.
    pub width: i64,
    /// The height of the screen in pixels.
    pub height: i64,
    /// Specifies the screen's work area. Default is entire screen.
    #[serde(
        rename = "workAreaInsets",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub work_area_insets: Option<WorkAreaInsets>,
    /// Specifies the screen's device pixel ratio. Default is 1.
    #[serde(
        rename = "devicePixelRatio",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub device_pixel_ratio: Option<f64>,
    /// Specifies the screen's rotation angle. Available values are 0, 90, 180 and
    /// 270. Default is 0.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rotation: Option<i64>,
    /// Specifies the screen's color depth in bits. Default is 24.
    #[serde(
        rename = "colorDepth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub color_depth: Option<i64>,
    /// Specifies the descriptive label for the screen. Default is none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Indicates whether the screen is internal to the device or external,
    /// attached to the device. Default is false.
    #[serde(
        rename = "isInternal",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_internal: Option<bool>,
}

/// What `Emulation.addScreen` answers with.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddScreenReturns {
    #[serde(rename = "screenInfo")]
    pub screen_info: ScreenInfo,
}

impl crate::typed::Command for AddScreenParams {
    const METHOD: &'static str = "Emulation.addScreen";
    type Returns = AddScreenReturns;
}

/// Updates specified screen parameters. Only supported in headless mode.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.updateScreen`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UpdateScreenParams {
    /// Target screen identifier.
    #[serde(rename = "screenId")]
    pub screen_id: ScreenId,
    /// Offset of the left edge of the screen in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub left: Option<i64>,
    /// Offset of the top edge of the screen in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top: Option<i64>,
    /// The width of the screen in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<i64>,
    /// The height of the screen in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    /// Specifies the screen's work area.
    #[serde(
        rename = "workAreaInsets",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub work_area_insets: Option<WorkAreaInsets>,
    /// Specifies the screen's device pixel ratio.
    #[serde(
        rename = "devicePixelRatio",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub device_pixel_ratio: Option<f64>,
    /// Specifies the screen's rotation angle. Available values are 0, 90, 180 and
    /// 270.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rotation: Option<i64>,
    /// Specifies the screen's color depth in bits.
    #[serde(
        rename = "colorDepth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub color_depth: Option<i64>,
    /// Specifies the descriptive label for the screen.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Indicates whether the screen is internal to the device or external,
    /// attached to the device. Default is false.
    #[serde(
        rename = "isInternal",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_internal: Option<bool>,
}

/// What `Emulation.updateScreen` answers with.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UpdateScreenReturns {
    #[serde(rename = "screenInfo")]
    pub screen_info: ScreenInfo,
}

impl crate::typed::Command for UpdateScreenParams {
    const METHOD: &'static str = "Emulation.updateScreen";
    type Returns = UpdateScreenReturns;
}

/// Remove screen from the device. Only supported in headless mode.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.removeScreen`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RemoveScreenParams {
    #[serde(rename = "screenId")]
    pub screen_id: ScreenId,
}

impl crate::typed::Command for RemoveScreenParams {
    const METHOD: &'static str = "Emulation.removeScreen";
    type Returns = crate::typed::NoReturns;
}

/// Set primary screen. Only supported in headless mode. Note that this
/// changes the coordinate system origin to the top-left of the new primary
/// screen, updating the bounds and work areas of all existing screens
/// accordingly.
///
/// Experimental: may change without notice.
///
/// Parameters of `Emulation.setPrimaryScreen`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetPrimaryScreenParams {
    #[serde(rename = "screenId")]
    pub screen_id: ScreenId,
}

impl crate::typed::Command for SetPrimaryScreenParams {
    const METHOD: &'static str = "Emulation.setPrimaryScreen";
    type Returns = crate::typed::NoReturns;
}

/// Notification sent after the virtual time budget for the current
/// VirtualTimePolicy has run out.
///
/// Experimental: may change without notice.
///
/// Payload of the `Emulation.virtualTimeBudgetExpired` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct VirtualTimeBudgetExpiredEvent {}

impl crate::typed::Event for VirtualTimeBudgetExpiredEvent {
    const METHOD: &'static str = "Emulation.virtualTimeBudgetExpired";
}

/// Fired when a page calls screen.orientation.lock() or
/// screen.orientation.unlock() while device emulation is enabled. This allows
/// the DevTools frontend to update the emulated device orientation
/// accordingly.
///
/// Experimental: may change without notice.
///
/// Payload of the `Emulation.screenOrientationLockChanged` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ScreenOrientationLockChangedEvent {
    /// Whether the screen orientation is currently locked.
    pub locked: bool,
    /// The orientation lock type requested by the page. Only set when locked is
    /// true.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub orientation: Option<ScreenOrientation>,
}

impl crate::typed::Event for ScreenOrientationLockChangedEvent {
    const METHOD: &'static str = "Emulation.screenOrientationLockChanged";
}
