// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! This domain provides experimental commands only supported in headless
//! mode.
//!
//! Types, command parameters and event payloads for the `HeadlessExperimental`
//! domain. The method-name constants for the same domain are in
//! [`crate::methods`].
//!
//! This domain is experimental and may change without notice.

use serde::{Deserialize, Serialize};

/// Encoding options for a screenshot.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotParams {
    /// Image compression format (defaults to png).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub format: Option<ScreenshotParamsFormat>,
    /// Compression quality from range \[0..100\] (jpeg and webp only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quality: Option<i64>,
    /// Optimize image encoding for speed, not for resulting size (defaults to
    /// false)
    #[serde(
        rename = "optimizeForSpeed",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optimize_for_speed: Option<bool>,
}

/// The values `format` accepts on `ScreenshotParams`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ScreenshotParamsFormat {
    /// `jpeg`
    #[serde(rename = "jpeg")]
    Jpeg,
    /// `png`
    #[serde(rename = "png")]
    Png,
    /// `webp`
    #[serde(rename = "webp")]
    Webp,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Sends a BeginFrame to the target and returns when the frame was completed.
/// Optionally captures a screenshot from the resulting frame. Requires that
/// the target was created with enabled BeginFrameControl. Designed for use
/// with --run-all-compositor-stages-before-draw, see also
/// <https://goo.gle/chrome-headless-rendering> for more background.
///
/// Parameters of `HeadlessExperimental.beginFrame`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct BeginFrameParams {
    /// Timestamp of this BeginFrame in Renderer TimeTicks (milliseconds of
    /// uptime). If not set, the current time will be used.
    #[serde(
        rename = "frameTimeTicks",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub frame_time_ticks: Option<f64>,
    /// The interval between BeginFrames that is reported to the compositor, in
    /// milliseconds. Defaults to a 60 frames/second interval, i.e. about 16.666
    /// milliseconds.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval: Option<f64>,
    /// Whether updates should not be committed and drawn onto the display. False
    /// by default. If true, only side effects of the BeginFrame will be run, such
    /// as layout and animations, but any visual updates may not be visible on the
    /// display or in screenshots.
    #[serde(
        rename = "noDisplayUpdates",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub no_display_updates: Option<bool>,
    /// If set, a screenshot of the frame will be captured and returned in the
    /// response. Otherwise, no screenshot will be captured. Note that capturing a
    /// screenshot can fail, for example, during renderer initialization. In such
    /// a case, no screenshot data will be returned.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub screenshot: Option<ScreenshotParams>,
}

/// What `HeadlessExperimental.beginFrame` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct BeginFrameReturns {
    /// Whether the BeginFrame resulted in damage and, thus, a new frame was
    /// committed to the display. Reported for diagnostic uses, may be removed in
    /// the future.
    #[serde(rename = "hasDamage")]
    pub has_damage: bool,
    /// Base64-encoded image data of the screenshot, if one was requested and
    /// successfully taken. (Encoded as a base64 string when passed over JSON)
    #[serde(
        rename = "screenshotData",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub screenshot_data: Option<String>,
}

impl crate::typed::Command for BeginFrameParams {
    const METHOD: &'static str = "HeadlessExperimental.beginFrame";
    type Returns = BeginFrameReturns;
}

/// Disables headless events for the target.
///
/// Deprecated in the protocol.
///
/// Parameters of `HeadlessExperimental.disable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DisableParams {}

impl crate::typed::Command for DisableParams {
    const METHOD: &'static str = "HeadlessExperimental.disable";
    type Returns = crate::typed::NoReturns;
}

/// Enables headless events for the target.
///
/// Deprecated in the protocol.
///
/// Parameters of `HeadlessExperimental.enable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnableParams {}

impl crate::typed::Command for EnableParams {
    const METHOD: &'static str = "HeadlessExperimental.enable";
    type Returns = crate::typed::NoReturns;
}
