// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! The `IndexedDB` domain.
//!
//! Types, command parameters and event payloads for the `IndexedDB`
//! domain. The method-name constants for the same domain are in
//! [`crate::methods`].
//!
//! This domain is experimental and may change without notice.

use serde::{Deserialize, Serialize};

/// Database with an array of object stores.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DatabaseWithObjectStores {
    /// Database name.
    pub name: String,
    /// Database version (type is not 'integer', as the standard requires the
    /// version number to be 'unsigned long long')
    pub version: f64,
    /// Object stores in this database.
    #[serde(rename = "objectStores")]
    pub object_stores: Vec<ObjectStore>,
}

/// Object store.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ObjectStore {
    /// Object store name.
    pub name: String,
    /// Object store key path.
    #[serde(rename = "keyPath")]
    pub key_path: KeyPath,
    /// If true, object store has auto increment flag set.
    #[serde(rename = "autoIncrement")]
    pub auto_increment: bool,
    /// Indexes in this object store.
    pub indexes: Vec<ObjectStoreIndex>,
}

/// Object store index.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ObjectStoreIndex {
    /// Index name.
    pub name: String,
    /// Index key path.
    #[serde(rename = "keyPath")]
    pub key_path: KeyPath,
    /// If true, index is unique.
    pub unique: bool,
    /// If true, index allows multiple entries for a key.
    #[serde(rename = "multiEntry")]
    pub multi_entry: bool,
}

/// Key.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Key {
    /// Key type.
    pub r#type: KeyType,
    /// Number value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub number: Option<f64>,
    /// String value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub string: Option<String>,
    /// Date value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date: Option<f64>,
    /// Array value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub array: Option<Vec<Key>>,
}

/// The values `type` accepts on `Key`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum KeyType {
    /// `number`
    #[serde(rename = "number")]
    Number,
    /// `string`
    #[serde(rename = "string")]
    String,
    /// `date`
    #[serde(rename = "date")]
    Date,
    /// `array`
    #[serde(rename = "array")]
    Array,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Key range.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct KeyRange {
    /// Lower bound.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lower: Option<Key>,
    /// Upper bound.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upper: Option<Key>,
    /// If true lower bound is open.
    #[serde(rename = "lowerOpen")]
    pub lower_open: bool,
    /// If true upper bound is open.
    #[serde(rename = "upperOpen")]
    pub upper_open: bool,
}

/// Data entry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DataEntry {
    /// Key object.
    pub key: crate::protocol::runtime::RemoteObject,
    /// Primary key object.
    #[serde(rename = "primaryKey")]
    pub primary_key: crate::protocol::runtime::RemoteObject,
    /// Value object.
    pub value: crate::protocol::runtime::RemoteObject,
}

/// Key path.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct KeyPath {
    /// Key path type.
    pub r#type: KeyPathType,
    /// String value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub string: Option<String>,
    /// Array value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub array: Option<Vec<String>>,
}

/// The values `type` accepts on `KeyPath`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum KeyPathType {
    /// `null`
    #[serde(rename = "null")]
    Null,
    /// `string`
    #[serde(rename = "string")]
    String,
    /// `array`
    #[serde(rename = "array")]
    Array,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Clears all entries from an object store.
///
/// Parameters of `IndexedDB.clearObjectStore`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ClearObjectStoreParams {
    /// At least and at most one of securityOrigin, storageKey, or storageBucket
    /// must be specified. Security origin.
    #[serde(
        rename = "securityOrigin",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub security_origin: Option<String>,
    /// Storage key.
    #[serde(
        rename = "storageKey",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_key: Option<String>,
    /// Storage bucket. If not specified, it uses the default bucket.
    #[serde(
        rename = "storageBucket",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_bucket: Option<crate::protocol::storage::StorageBucket>,
    /// Database name.
    #[serde(rename = "databaseName")]
    pub database_name: String,
    /// Object store name.
    #[serde(rename = "objectStoreName")]
    pub object_store_name: String,
}

impl crate::typed::Command for ClearObjectStoreParams {
    const METHOD: &'static str = "IndexedDB.clearObjectStore";
    type Returns = crate::typed::NoReturns;
}

/// Deletes a database.
///
/// Parameters of `IndexedDB.deleteDatabase`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DeleteDatabaseParams {
    /// At least and at most one of securityOrigin, storageKey, or storageBucket
    /// must be specified. Security origin.
    #[serde(
        rename = "securityOrigin",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub security_origin: Option<String>,
    /// Storage key.
    #[serde(
        rename = "storageKey",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_key: Option<String>,
    /// Storage bucket. If not specified, it uses the default bucket.
    #[serde(
        rename = "storageBucket",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_bucket: Option<crate::protocol::storage::StorageBucket>,
    /// Database name.
    #[serde(rename = "databaseName")]
    pub database_name: String,
}

impl crate::typed::Command for DeleteDatabaseParams {
    const METHOD: &'static str = "IndexedDB.deleteDatabase";
    type Returns = crate::typed::NoReturns;
}

/// Delete a range of entries from an object store
///
/// Parameters of `IndexedDB.deleteObjectStoreEntries`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DeleteObjectStoreEntriesParams {
    /// At least and at most one of securityOrigin, storageKey, or storageBucket
    /// must be specified. Security origin.
    #[serde(
        rename = "securityOrigin",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub security_origin: Option<String>,
    /// Storage key.
    #[serde(
        rename = "storageKey",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_key: Option<String>,
    /// Storage bucket. If not specified, it uses the default bucket.
    #[serde(
        rename = "storageBucket",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_bucket: Option<crate::protocol::storage::StorageBucket>,
    #[serde(rename = "databaseName")]
    pub database_name: String,
    #[serde(rename = "objectStoreName")]
    pub object_store_name: String,
    /// Range of entry keys to delete
    #[serde(rename = "keyRange")]
    pub key_range: KeyRange,
}

impl crate::typed::Command for DeleteObjectStoreEntriesParams {
    const METHOD: &'static str = "IndexedDB.deleteObjectStoreEntries";
    type Returns = crate::typed::NoReturns;
}

/// Disables events from backend.
///
/// Parameters of `IndexedDB.disable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DisableParams {}

impl crate::typed::Command for DisableParams {
    const METHOD: &'static str = "IndexedDB.disable";
    type Returns = crate::typed::NoReturns;
}

/// Enables events from backend.
///
/// Parameters of `IndexedDB.enable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnableParams {}

impl crate::typed::Command for EnableParams {
    const METHOD: &'static str = "IndexedDB.enable";
    type Returns = crate::typed::NoReturns;
}

/// Requests data from object store or index.
///
/// Parameters of `IndexedDB.requestData`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RequestDataParams {
    /// At least and at most one of securityOrigin, storageKey, or storageBucket
    /// must be specified. Security origin.
    #[serde(
        rename = "securityOrigin",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub security_origin: Option<String>,
    /// Storage key.
    #[serde(
        rename = "storageKey",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_key: Option<String>,
    /// Storage bucket. If not specified, it uses the default bucket.
    #[serde(
        rename = "storageBucket",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_bucket: Option<crate::protocol::storage::StorageBucket>,
    /// Database name.
    #[serde(rename = "databaseName")]
    pub database_name: String,
    /// Object store name.
    #[serde(rename = "objectStoreName")]
    pub object_store_name: String,
    /// Index name. If not specified, it performs an object store data request.
    #[serde(rename = "indexName", default, skip_serializing_if = "Option::is_none")]
    pub index_name: Option<String>,
    /// Number of records to skip.
    #[serde(rename = "skipCount")]
    pub skip_count: i64,
    /// Number of records to fetch.
    #[serde(rename = "pageSize")]
    pub page_size: i64,
    /// Key range.
    #[serde(rename = "keyRange", default, skip_serializing_if = "Option::is_none")]
    pub key_range: Option<KeyRange>,
}

/// What `IndexedDB.requestData` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RequestDataReturns {
    /// Array of object store data entries.
    #[serde(rename = "objectStoreDataEntries")]
    pub object_store_data_entries: Vec<DataEntry>,
    /// If true, there are more entries to fetch in the given range.
    #[serde(rename = "hasMore")]
    pub has_more: bool,
}

impl crate::typed::Command for RequestDataParams {
    const METHOD: &'static str = "IndexedDB.requestData";
    type Returns = RequestDataReturns;
}

/// Gets metadata of an object store.
///
/// Parameters of `IndexedDB.getMetadata`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetMetadataParams {
    /// At least and at most one of securityOrigin, storageKey, or storageBucket
    /// must be specified. Security origin.
    #[serde(
        rename = "securityOrigin",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub security_origin: Option<String>,
    /// Storage key.
    #[serde(
        rename = "storageKey",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_key: Option<String>,
    /// Storage bucket. If not specified, it uses the default bucket.
    #[serde(
        rename = "storageBucket",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_bucket: Option<crate::protocol::storage::StorageBucket>,
    /// Database name.
    #[serde(rename = "databaseName")]
    pub database_name: String,
    /// Object store name.
    #[serde(rename = "objectStoreName")]
    pub object_store_name: String,
}

/// What `IndexedDB.getMetadata` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetMetadataReturns {
    /// the entries count
    #[serde(rename = "entriesCount")]
    pub entries_count: f64,
    /// the current value of key generator, to become the next inserted key into
    /// the object store. Valid if objectStore.autoIncrement is true.
    #[serde(rename = "keyGeneratorValue")]
    pub key_generator_value: f64,
}

impl crate::typed::Command for GetMetadataParams {
    const METHOD: &'static str = "IndexedDB.getMetadata";
    type Returns = GetMetadataReturns;
}

/// Requests database with given name in given frame.
///
/// Parameters of `IndexedDB.requestDatabase`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RequestDatabaseParams {
    /// At least and at most one of securityOrigin, storageKey, or storageBucket
    /// must be specified. Security origin.
    #[serde(
        rename = "securityOrigin",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub security_origin: Option<String>,
    /// Storage key.
    #[serde(
        rename = "storageKey",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_key: Option<String>,
    /// Storage bucket. If not specified, it uses the default bucket.
    #[serde(
        rename = "storageBucket",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_bucket: Option<crate::protocol::storage::StorageBucket>,
    /// Database name.
    #[serde(rename = "databaseName")]
    pub database_name: String,
}

/// What `IndexedDB.requestDatabase` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RequestDatabaseReturns {
    /// Database with an array of object stores.
    #[serde(rename = "databaseWithObjectStores")]
    pub database_with_object_stores: DatabaseWithObjectStores,
}

impl crate::typed::Command for RequestDatabaseParams {
    const METHOD: &'static str = "IndexedDB.requestDatabase";
    type Returns = RequestDatabaseReturns;
}

/// Requests database names for given security origin.
///
/// Parameters of `IndexedDB.requestDatabaseNames`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RequestDatabaseNamesParams {
    /// At least and at most one of securityOrigin, storageKey, or storageBucket
    /// must be specified. Security origin.
    #[serde(
        rename = "securityOrigin",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub security_origin: Option<String>,
    /// Storage key.
    #[serde(
        rename = "storageKey",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_key: Option<String>,
    /// Storage bucket. If not specified, it uses the default bucket.
    #[serde(
        rename = "storageBucket",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_bucket: Option<crate::protocol::storage::StorageBucket>,
}

/// What `IndexedDB.requestDatabaseNames` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RequestDatabaseNamesReturns {
    /// Database names for origin.
    #[serde(rename = "databaseNames")]
    pub database_names: Vec<String>,
}

impl crate::typed::Command for RequestDatabaseNamesParams {
    const METHOD: &'static str = "IndexedDB.requestDatabaseNames";
    type Returns = RequestDatabaseNamesReturns;
}
