// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! The `Preload` domain.
//!
//! Types, command parameters and event payloads for the `Preload`
//! domain. The method-name constants for the same domain are in
//! [`crate::methods`].
//!
//! This domain is experimental and may change without notice.

use serde::{Deserialize, Serialize};

/// Unique id
pub type RuleSetId = String;

/// Corresponds to SpeculationRuleSet
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RuleSet {
    pub id: RuleSetId,
    /// Identifies a document which the rule set is associated with.
    #[serde(rename = "loaderId")]
    pub loader_id: crate::protocol::network::LoaderId,
    /// Source text of JSON representing the rule set. If it comes from
    /// `\<script\>` tag, it is the textContent of the node. Note that it is a
    /// JSON for valid case. See also: -
    /// <https://wicg.github.io/nav-speculation/speculation-rules.html> -
    /// <https://github.com/WICG/nav-speculation/blob/main/triggers.md>
    #[serde(rename = "sourceText")]
    pub source_text: String,
    /// A speculation rule set is either added through an inline `\<script\>` tag
    /// or through an external resource via the 'Speculation-Rules' HTTP header.
    /// For the first case, we include the BackendNodeId of the relevant
    /// `\<script\>` tag. For the second case, we include the external URL where
    /// the rule set was loaded from, and also RequestId if Network domain is
    /// enabled. See also: -
    /// <https://wicg.github.io/nav-speculation/speculation-rules.html#speculation-rules-script>
    /// -
    /// <https://wicg.github.io/nav-speculation/speculation-rules.html#speculation-rules-header>
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<crate::protocol::dom::BackendNodeId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "requestId", default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<crate::protocol::network::RequestId>,
    /// Error information `errorMessage` is null iff `errorType` is null.
    #[serde(rename = "errorType", default, skip_serializing_if = "Option::is_none")]
    pub error_type: Option<RuleSetErrorType>,
    /// TODO(<https://crbug.com/1425354>): Replace this property with structured
    /// error.
    ///
    /// Deprecated in the protocol.
    #[serde(
        rename = "errorMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error_message: Option<String>,
    /// For more details, see:
    /// <https://github.com/WICG/nav-speculation/blob/main/speculation-rules-tags.md>
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RuleSetErrorType {
    /// `SourceIsNotJsonObject`
    SourceIsNotJsonObject,
    /// `InvalidRulesSkipped`
    InvalidRulesSkipped,
    /// `InvalidRulesetLevelTag`
    InvalidRulesetLevelTag,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// The type of preloading attempted. It corresponds to
/// mojom::SpeculationAction (although PrefetchWithSubresources is omitted as
/// it isn't being used by clients).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SpeculationAction {
    /// `Prefetch`
    Prefetch,
    /// `Prerender`
    Prerender,
    /// `PrerenderUntilScript`
    PrerenderUntilScript,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Corresponds to mojom::SpeculationTargetHint. See
/// <https://github.com/WICG/nav-speculation/blob/main/triggers.md#window-name-targeting-hints>
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SpeculationTargetHint {
    /// `Blank`
    Blank,
    /// `Self`
    #[serde(rename = "Self")]
    Self_,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// A key that identifies a preloading attempt. The url used is the url
/// specified by the trigger (i.e. the initial URL), and not the final url
/// that is navigated to. For example, prerendering allows same-origin main
/// frame navigations during the attempt, but the attempt is still keyed with
/// the initial URL.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreloadingAttemptKey {
    #[serde(rename = "loaderId")]
    pub loader_id: crate::protocol::network::LoaderId,
    pub action: SpeculationAction,
    pub url: String,
    #[serde(
        rename = "formSubmission",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub form_submission: Option<bool>,
    #[serde(
        rename = "targetHint",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub target_hint: Option<SpeculationTargetHint>,
}

/// Lists sources for a preloading attempt, specifically the ids of rule sets
/// that had a speculation rule that triggered the attempt, and the
/// BackendNodeIds of \<a href\> or \<area href\> elements that triggered the
/// attempt (in the case of attempts triggered by a document rule). It is
/// possible for multiple rule sets and links to trigger a single attempt.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreloadingAttemptSource {
    pub key: PreloadingAttemptKey,
    #[serde(rename = "ruleSetIds")]
    pub rule_set_ids: Vec<RuleSetId>,
    #[serde(rename = "nodeIds")]
    pub node_ids: Vec<crate::protocol::dom::BackendNodeId>,
}

/// Chrome manages different types of preloads together using a concept of
/// preloading pipeline. For example, if a site uses a SpeculationRules for
/// prerender, Chrome first starts a prefetch and then upgrades it to
/// prerender. CDP events for them are emitted separately but they share
/// `PreloadPipelineId`.
pub type PreloadPipelineId = String;

/// List of FinalStatus reasons for Prerender2.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PrerenderFinalStatus {
    /// `Activated`
    Activated,
    /// `Destroyed`
    Destroyed,
    /// `LowEndDevice`
    LowEndDevice,
    /// `InvalidSchemeRedirect`
    InvalidSchemeRedirect,
    /// `InvalidSchemeNavigation`
    InvalidSchemeNavigation,
    /// `NavigationRequestBlockedByCsp`
    NavigationRequestBlockedByCsp,
    /// `MojoBinderPolicy`
    MojoBinderPolicy,
    /// `RendererProcessCrashed`
    RendererProcessCrashed,
    /// `RendererProcessKilled`
    RendererProcessKilled,
    /// `Download`
    Download,
    /// `TriggerDestroyed`
    TriggerDestroyed,
    /// `NavigationNotCommitted`
    NavigationNotCommitted,
    /// `NavigationBadHttpStatus`
    NavigationBadHttpStatus,
    /// `ClientCertRequested`
    ClientCertRequested,
    /// `NavigationRequestNetworkError`
    NavigationRequestNetworkError,
    /// `CancelAllHostsForTesting`
    CancelAllHostsForTesting,
    /// `DidFailLoad`
    DidFailLoad,
    /// `Stop`
    Stop,
    /// `SslCertificateError`
    SslCertificateError,
    /// `LoginAuthRequested`
    LoginAuthRequested,
    /// `UaChangeRequiresReload`
    UaChangeRequiresReload,
    /// `BlockedByClient`
    BlockedByClient,
    /// `AudioOutputDeviceRequested`
    AudioOutputDeviceRequested,
    /// `MixedContent`
    MixedContent,
    /// `TriggerBackgrounded`
    TriggerBackgrounded,
    /// `MemoryLimitExceeded`
    MemoryLimitExceeded,
    /// `DataSaverEnabled`
    DataSaverEnabled,
    /// `TriggerUrlHasEffectiveUrl`
    TriggerUrlHasEffectiveUrl,
    /// `ActivatedBeforeStarted`
    ActivatedBeforeStarted,
    /// `InactivePageRestriction`
    InactivePageRestriction,
    /// `StartFailed`
    StartFailed,
    /// `TimeoutBackgrounded`
    TimeoutBackgrounded,
    /// `CrossSiteRedirectInInitialNavigation`
    CrossSiteRedirectInInitialNavigation,
    /// `CrossSiteNavigationInInitialNavigation`
    CrossSiteNavigationInInitialNavigation,
    /// `SameSiteCrossOriginRedirectNotOptInInInitialNavigation`
    SameSiteCrossOriginRedirectNotOptInInInitialNavigation,
    /// `SameSiteCrossOriginNavigationNotOptInInInitialNavigation`
    SameSiteCrossOriginNavigationNotOptInInInitialNavigation,
    /// `ActivationNavigationParameterMismatch`
    ActivationNavigationParameterMismatch,
    /// `ActivatedInBackground`
    ActivatedInBackground,
    /// `EmbedderHostDisallowed`
    EmbedderHostDisallowed,
    /// `ActivationNavigationDestroyedBeforeSuccess`
    ActivationNavigationDestroyedBeforeSuccess,
    /// `TabClosedByUserGesture`
    TabClosedByUserGesture,
    /// `TabClosedWithoutUserGesture`
    TabClosedWithoutUserGesture,
    /// `PrimaryMainFrameRendererProcessCrashed`
    PrimaryMainFrameRendererProcessCrashed,
    /// `PrimaryMainFrameRendererProcessKilled`
    PrimaryMainFrameRendererProcessKilled,
    /// `ActivationFramePolicyNotCompatible`
    ActivationFramePolicyNotCompatible,
    /// `PreloadingDisabled`
    PreloadingDisabled,
    /// `BatterySaverEnabled`
    BatterySaverEnabled,
    /// `ActivatedDuringMainFrameNavigation`
    ActivatedDuringMainFrameNavigation,
    /// `PreloadingUnsupportedByWebContents`
    PreloadingUnsupportedByWebContents,
    /// `CrossSiteRedirectInMainFrameNavigation`
    CrossSiteRedirectInMainFrameNavigation,
    /// `CrossSiteNavigationInMainFrameNavigation`
    CrossSiteNavigationInMainFrameNavigation,
    /// `SameSiteCrossOriginRedirectNotOptInInMainFrameNavigation`
    SameSiteCrossOriginRedirectNotOptInInMainFrameNavigation,
    /// `SameSiteCrossOriginNavigationNotOptInInMainFrameNavigation`
    SameSiteCrossOriginNavigationNotOptInInMainFrameNavigation,
    /// `MemoryPressureOnTrigger`
    MemoryPressureOnTrigger,
    /// `MemoryPressureAfterTriggered`
    MemoryPressureAfterTriggered,
    /// `PrerenderingDisabledByDevTools`
    PrerenderingDisabledByDevTools,
    /// `SpeculationRuleRemoved`
    SpeculationRuleRemoved,
    /// `ActivatedWithAuxiliaryBrowsingContexts`
    ActivatedWithAuxiliaryBrowsingContexts,
    /// `MaxNumOfRunningEagerPrerendersExceeded`
    MaxNumOfRunningEagerPrerendersExceeded,
    /// `MaxNumOfRunningNonEagerPrerendersExceeded`
    MaxNumOfRunningNonEagerPrerendersExceeded,
    /// `MaxNumOfRunningEmbedderPrerendersExceeded`
    MaxNumOfRunningEmbedderPrerendersExceeded,
    /// `PrerenderingUrlHasEffectiveUrl`
    PrerenderingUrlHasEffectiveUrl,
    /// `RedirectedPrerenderingUrlHasEffectiveUrl`
    RedirectedPrerenderingUrlHasEffectiveUrl,
    /// `ActivationUrlHasEffectiveUrl`
    ActivationUrlHasEffectiveUrl,
    /// `JavaScriptInterfaceAdded`
    JavaScriptInterfaceAdded,
    /// `JavaScriptInterfaceRemoved`
    JavaScriptInterfaceRemoved,
    /// `AllPrerenderingCanceled`
    AllPrerenderingCanceled,
    /// `WindowClosed`
    WindowClosed,
    /// `SlowNetwork`
    SlowNetwork,
    /// `OtherPrerenderedPageActivated`
    OtherPrerenderedPageActivated,
    /// `V8OptimizerDisabled`
    V8OptimizerDisabled,
    /// `PrerenderFailedDuringPrefetch`
    PrerenderFailedDuringPrefetch,
    /// `BrowsingDataRemoved`
    BrowsingDataRemoved,
    /// `PrerenderHostReused`
    PrerenderHostReused,
    /// `FormSubmitWhenPrerendering`
    FormSubmitWhenPrerendering,
    /// `CrossDocumentRestart`
    CrossDocumentRestart,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Preloading status values, see also PreloadingTriggeringOutcome. This
/// status is shared by prefetchStatusUpdated and prerenderStatusUpdated.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PreloadingStatus {
    /// `Pending`
    Pending,
    /// `Running`
    Running,
    /// `Ready`
    Ready,
    /// `Success`
    Success,
    /// `Failure`
    Failure,
    /// `NotSupported`
    NotSupported,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// TODO(<https://crbug.com/1384419>): revisit the list of PrefetchStatus and
/// filter out the ones that aren't necessary to the developers.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PrefetchStatus {
    /// `PrefetchAllowed`
    PrefetchAllowed,
    /// `PrefetchFailedIneligibleRedirect`
    PrefetchFailedIneligibleRedirect,
    /// `PrefetchFailedInvalidRedirect`
    PrefetchFailedInvalidRedirect,
    /// `PrefetchFailedMIMENotSupported`
    #[serde(rename = "PrefetchFailedMIMENotSupported")]
    PrefetchFailedMimeNotSupported,
    /// `PrefetchFailedNetError`
    PrefetchFailedNetError,
    /// `PrefetchFailedNon2XX`
    #[serde(rename = "PrefetchFailedNon2XX")]
    PrefetchFailedNon2Xx,
    /// `PrefetchEvictedAfterBrowsingDataRemoved`
    PrefetchEvictedAfterBrowsingDataRemoved,
    /// `PrefetchEvictedAfterCandidateRemoved`
    PrefetchEvictedAfterCandidateRemoved,
    /// `PrefetchEvictedForNewerPrefetch`
    PrefetchEvictedForNewerPrefetch,
    /// `PrefetchHeldback`
    PrefetchHeldback,
    /// `PrefetchIneligibleRetryAfter`
    PrefetchIneligibleRetryAfter,
    /// `PrefetchIsPrivacyDecoy`
    PrefetchIsPrivacyDecoy,
    /// `PrefetchIsStale`
    PrefetchIsStale,
    /// `PrefetchNotEligibleBlockedByConnectionAllowlist`
    PrefetchNotEligibleBlockedByConnectionAllowlist,
    /// `PrefetchNotEligibleBrowserContextOffTheRecord`
    PrefetchNotEligibleBrowserContextOffTheRecord,
    /// `PrefetchNotEligibleDataSaverEnabled`
    PrefetchNotEligibleDataSaverEnabled,
    /// `PrefetchNotEligibleExistingProxy`
    PrefetchNotEligibleExistingProxy,
    /// `PrefetchNotEligibleHostIsNonUnique`
    PrefetchNotEligibleHostIsNonUnique,
    /// `PrefetchNotEligibleNonDefaultStoragePartition`
    PrefetchNotEligibleNonDefaultStoragePartition,
    /// `PrefetchNotEligibleSameSiteCrossOriginPrefetchRequiredProxy`
    PrefetchNotEligibleSameSiteCrossOriginPrefetchRequiredProxy,
    /// `PrefetchNotEligibleSchemeIsNotHttps`
    PrefetchNotEligibleSchemeIsNotHttps,
    /// `PrefetchNotEligibleUserHasCookies`
    PrefetchNotEligibleUserHasCookies,
    /// `PrefetchNotEligibleUserHasServiceWorker`
    PrefetchNotEligibleUserHasServiceWorker,
    /// `PrefetchNotEligibleUserHasServiceWorkerNoFetchHandler`
    PrefetchNotEligibleUserHasServiceWorkerNoFetchHandler,
    /// `PrefetchNotEligibleRedirectFromServiceWorker`
    PrefetchNotEligibleRedirectFromServiceWorker,
    /// `PrefetchNotEligibleRedirectToServiceWorker`
    PrefetchNotEligibleRedirectToServiceWorker,
    /// `PrefetchNotEligibleBatterySaverEnabled`
    PrefetchNotEligibleBatterySaverEnabled,
    /// `PrefetchNotEligiblePreloadingDisabled`
    PrefetchNotEligiblePreloadingDisabled,
    /// `PrefetchNotFinishedInTime`
    PrefetchNotFinishedInTime,
    /// `PrefetchNotStarted`
    PrefetchNotStarted,
    /// `PrefetchNotUsedCookiesChanged`
    PrefetchNotUsedCookiesChanged,
    /// `PrefetchProxyNotAvailable`
    PrefetchProxyNotAvailable,
    /// `PrefetchResponseUsed`
    PrefetchResponseUsed,
    /// `PrefetchSuccessfulButNotUsed`
    PrefetchSuccessfulButNotUsed,
    /// `PrefetchNotUsedProbeFailed`
    PrefetchNotUsedProbeFailed,
    /// `PrefetchCancelledOnUserNavigation`
    PrefetchCancelledOnUserNavigation,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Information of headers to be displayed when the header mismatch occurred.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PrerenderMismatchedHeaders {
    #[serde(rename = "headerName")]
    pub header_name: String,
    #[serde(
        rename = "initialValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub initial_value: Option<String>,
    #[serde(
        rename = "activationValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub activation_value: Option<String>,
}

/// Parameters of `Preload.enable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnableParams {}

impl crate::typed::Command for EnableParams {
    const METHOD: &'static str = "Preload.enable";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `Preload.disable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DisableParams {}

impl crate::typed::Command for DisableParams {
    const METHOD: &'static str = "Preload.disable";
    type Returns = crate::typed::NoReturns;
}

/// Upsert. Currently, it is only emitted when a rule set added.
///
/// Payload of the `Preload.ruleSetUpdated` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RuleSetUpdatedEvent {
    #[serde(rename = "ruleSet")]
    pub rule_set: RuleSet,
}

impl crate::typed::Event for RuleSetUpdatedEvent {
    const METHOD: &'static str = "Preload.ruleSetUpdated";
}

/// Payload of the `Preload.ruleSetRemoved` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RuleSetRemovedEvent {
    pub id: RuleSetId,
}

impl crate::typed::Event for RuleSetRemovedEvent {
    const METHOD: &'static str = "Preload.ruleSetRemoved";
}

/// Fired when a preload enabled state is updated.
///
/// Payload of the `Preload.preloadEnabledStateUpdated` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PreloadEnabledStateUpdatedEvent {
    #[serde(rename = "disabledByPreference")]
    pub disabled_by_preference: bool,
    #[serde(rename = "disabledByDataSaver")]
    pub disabled_by_data_saver: bool,
    #[serde(rename = "disabledByBatterySaver")]
    pub disabled_by_battery_saver: bool,
    #[serde(rename = "disabledByHoldbackPrefetchSpeculationRules")]
    pub disabled_by_holdback_prefetch_speculation_rules: bool,
    #[serde(rename = "disabledByHoldbackPrerenderSpeculationRules")]
    pub disabled_by_holdback_prerender_speculation_rules: bool,
}

impl crate::typed::Event for PreloadEnabledStateUpdatedEvent {
    const METHOD: &'static str = "Preload.preloadEnabledStateUpdated";
}

/// Fired when a prefetch attempt is updated.
///
/// Payload of the `Preload.prefetchStatusUpdated` event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PrefetchStatusUpdatedEvent {
    pub key: PreloadingAttemptKey,
    #[serde(rename = "pipelineId")]
    pub pipeline_id: PreloadPipelineId,
    /// The frame id of the frame initiating prefetch.
    #[serde(rename = "initiatingFrameId")]
    pub initiating_frame_id: crate::protocol::page::FrameId,
    #[serde(rename = "prefetchUrl")]
    pub prefetch_url: String,
    pub status: PreloadingStatus,
    #[serde(rename = "prefetchStatus")]
    pub prefetch_status: PrefetchStatus,
    #[serde(rename = "requestId")]
    pub request_id: crate::protocol::network::RequestId,
}

impl crate::typed::Event for PrefetchStatusUpdatedEvent {
    const METHOD: &'static str = "Preload.prefetchStatusUpdated";
}

/// Fired when a prerender attempt is updated.
///
/// Payload of the `Preload.prerenderStatusUpdated` event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PrerenderStatusUpdatedEvent {
    pub key: PreloadingAttemptKey,
    #[serde(rename = "pipelineId")]
    pub pipeline_id: PreloadPipelineId,
    pub status: PreloadingStatus,
    #[serde(
        rename = "prerenderStatus",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub prerender_status: Option<PrerenderFinalStatus>,
    /// This is used to give users more information about the name of Mojo
    /// interface that is incompatible with prerender and has caused the
    /// cancellation of the attempt.
    #[serde(
        rename = "disallowedMojoInterface",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub disallowed_mojo_interface: Option<String>,
    #[serde(
        rename = "mismatchedHeaders",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub mismatched_headers: Option<Vec<PrerenderMismatchedHeaders>>,
}

impl crate::typed::Event for PrerenderStatusUpdatedEvent {
    const METHOD: &'static str = "Preload.prerenderStatusUpdated";
}

/// Send a list of sources for all preloading attempts in a document.
///
/// Payload of the `Preload.preloadingAttemptSourcesUpdated` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PreloadingAttemptSourcesUpdatedEvent {
    #[serde(rename = "loaderId")]
    pub loader_id: crate::protocol::network::LoaderId,
    #[serde(rename = "preloadingAttemptSources")]
    pub preloading_attempt_sources: Vec<PreloadingAttemptSource>,
}

impl crate::typed::Event for PreloadingAttemptSourcesUpdatedEvent {
    const METHOD: &'static str = "Preload.preloadingAttemptSourcesUpdated";
}
