// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! The `ServiceWorker` domain.
//!
//! Types, command parameters and event payloads for the `ServiceWorker`
//! domain. The method-name constants for the same domain are in
//! [`crate::methods`].
//!
//! This domain is experimental and may change without notice.

use serde::{Deserialize, Serialize};

pub type RegistrationId = String;

/// ServiceWorker registration.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ServiceWorkerRegistration {
    #[serde(rename = "registrationId")]
    pub registration_id: RegistrationId,
    #[serde(rename = "scopeURL")]
    pub scope_url: String,
    #[serde(rename = "isDeleted")]
    pub is_deleted: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ServiceWorkerVersionRunningStatus {
    /// `stopped`
    #[serde(rename = "stopped")]
    Stopped,
    /// `starting`
    #[serde(rename = "starting")]
    Starting,
    /// `running`
    #[serde(rename = "running")]
    Running,
    /// `stopping`
    #[serde(rename = "stopping")]
    Stopping,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ServiceWorkerVersionStatus {
    /// `new`
    #[serde(rename = "new")]
    New,
    /// `installing`
    #[serde(rename = "installing")]
    Installing,
    /// `installed`
    #[serde(rename = "installed")]
    Installed,
    /// `activating`
    #[serde(rename = "activating")]
    Activating,
    /// `activated`
    #[serde(rename = "activated")]
    Activated,
    /// `redundant`
    #[serde(rename = "redundant")]
    Redundant,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// ServiceWorker version.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ServiceWorkerVersion {
    #[serde(rename = "versionId")]
    pub version_id: String,
    #[serde(rename = "registrationId")]
    pub registration_id: RegistrationId,
    #[serde(rename = "scriptURL")]
    pub script_url: String,
    #[serde(rename = "runningStatus")]
    pub running_status: ServiceWorkerVersionRunningStatus,
    pub status: ServiceWorkerVersionStatus,
    /// The Last-Modified header value of the main script.
    #[serde(
        rename = "scriptLastModified",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub script_last_modified: Option<f64>,
    /// The time at which the response headers of the main script were received
    /// from the server. For cached script it is the last time the cache entry was
    /// validated.
    #[serde(
        rename = "scriptResponseTime",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub script_response_time: Option<f64>,
    #[serde(
        rename = "controlledClients",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub controlled_clients: Option<Vec<crate::protocol::target::TargetId>>,
    #[serde(rename = "targetId", default, skip_serializing_if = "Option::is_none")]
    pub target_id: Option<crate::protocol::target::TargetId>,
    #[serde(
        rename = "routerRules",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub router_rules: Option<String>,
}

/// ServiceWorker error message.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ServiceWorkerErrorMessage {
    #[serde(rename = "errorMessage")]
    pub error_message: String,
    #[serde(rename = "registrationId")]
    pub registration_id: RegistrationId,
    #[serde(rename = "versionId")]
    pub version_id: String,
    #[serde(rename = "sourceURL")]
    pub source_url: String,
    #[serde(rename = "lineNumber")]
    pub line_number: i64,
    #[serde(rename = "columnNumber")]
    pub column_number: i64,
}

/// Parameters of `ServiceWorker.deliverPushMessage`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DeliverPushMessageParams {
    pub origin: String,
    #[serde(rename = "registrationId")]
    pub registration_id: RegistrationId,
    pub data: String,
}

impl crate::typed::Command for DeliverPushMessageParams {
    const METHOD: &'static str = "ServiceWorker.deliverPushMessage";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.disable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DisableParams {}

impl crate::typed::Command for DisableParams {
    const METHOD: &'static str = "ServiceWorker.disable";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.dispatchSyncEvent`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DispatchSyncEventParams {
    pub origin: String,
    #[serde(rename = "registrationId")]
    pub registration_id: RegistrationId,
    pub tag: String,
    #[serde(rename = "lastChance")]
    pub last_chance: bool,
}

impl crate::typed::Command for DispatchSyncEventParams {
    const METHOD: &'static str = "ServiceWorker.dispatchSyncEvent";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.dispatchPeriodicSyncEvent`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DispatchPeriodicSyncEventParams {
    pub origin: String,
    #[serde(rename = "registrationId")]
    pub registration_id: RegistrationId,
    pub tag: String,
}

impl crate::typed::Command for DispatchPeriodicSyncEventParams {
    const METHOD: &'static str = "ServiceWorker.dispatchPeriodicSyncEvent";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.enable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnableParams {}

impl crate::typed::Command for EnableParams {
    const METHOD: &'static str = "ServiceWorker.enable";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.setForceUpdateOnPageLoad`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SetForceUpdateOnPageLoadParams {
    #[serde(rename = "forceUpdateOnPageLoad")]
    pub force_update_on_page_load: bool,
}

impl crate::typed::Command for SetForceUpdateOnPageLoadParams {
    const METHOD: &'static str = "ServiceWorker.setForceUpdateOnPageLoad";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.skipWaiting`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SkipWaitingParams {
    #[serde(rename = "scopeURL")]
    pub scope_url: String,
}

impl crate::typed::Command for SkipWaitingParams {
    const METHOD: &'static str = "ServiceWorker.skipWaiting";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.startWorker`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StartWorkerParams {
    #[serde(rename = "scopeURL")]
    pub scope_url: String,
}

impl crate::typed::Command for StartWorkerParams {
    const METHOD: &'static str = "ServiceWorker.startWorker";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.stopAllWorkers`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StopAllWorkersParams {}

impl crate::typed::Command for StopAllWorkersParams {
    const METHOD: &'static str = "ServiceWorker.stopAllWorkers";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.stopWorker`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StopWorkerParams {
    #[serde(rename = "versionId")]
    pub version_id: String,
}

impl crate::typed::Command for StopWorkerParams {
    const METHOD: &'static str = "ServiceWorker.stopWorker";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.unregister`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UnregisterParams {
    #[serde(rename = "scopeURL")]
    pub scope_url: String,
}

impl crate::typed::Command for UnregisterParams {
    const METHOD: &'static str = "ServiceWorker.unregister";
    type Returns = crate::typed::NoReturns;
}

/// Parameters of `ServiceWorker.updateRegistration`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UpdateRegistrationParams {
    #[serde(rename = "scopeURL")]
    pub scope_url: String,
}

impl crate::typed::Command for UpdateRegistrationParams {
    const METHOD: &'static str = "ServiceWorker.updateRegistration";
    type Returns = crate::typed::NoReturns;
}

/// Payload of the `ServiceWorker.workerErrorReported` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerErrorReportedEvent {
    #[serde(rename = "errorMessage")]
    pub error_message: ServiceWorkerErrorMessage,
}

impl crate::typed::Event for WorkerErrorReportedEvent {
    const METHOD: &'static str = "ServiceWorker.workerErrorReported";
}

/// Payload of the `ServiceWorker.workerRegistrationUpdated` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerRegistrationUpdatedEvent {
    pub registrations: Vec<ServiceWorkerRegistration>,
}

impl crate::typed::Event for WorkerRegistrationUpdatedEvent {
    const METHOD: &'static str = "ServiceWorker.workerRegistrationUpdated";
}

/// Payload of the `ServiceWorker.workerVersionUpdated` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkerVersionUpdatedEvent {
    pub versions: Vec<ServiceWorkerVersion>,
}

impl crate::typed::Event for WorkerVersionUpdatedEvent {
    const METHOD: &'static str = "ServiceWorker.workerVersionUpdated";
}
