// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! This domain allows inspection of Web Audio API.
//! <https://webaudio.github.io/web-audio-api/>
//!
//! Types, command parameters and event payloads for the `WebAudio`
//! domain. The method-name constants for the same domain are in
//! [`crate::methods`].
//!
//! This domain is experimental and may change without notice.

use serde::{Deserialize, Serialize};

/// An unique ID for a graph object (AudioContext, AudioNode, AudioParam) in
/// Web Audio API
pub type GraphObjectId = String;

/// Enum of BaseAudioContext types
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ContextType {
    /// `realtime`
    #[serde(rename = "realtime")]
    Realtime,
    /// `offline`
    #[serde(rename = "offline")]
    Offline,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Enum of AudioContextState from the spec
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ContextState {
    /// `suspended`
    #[serde(rename = "suspended")]
    Suspended,
    /// `running`
    #[serde(rename = "running")]
    Running,
    /// `closed`
    #[serde(rename = "closed")]
    Closed,
    /// `interrupted`
    #[serde(rename = "interrupted")]
    Interrupted,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Enum of AudioNode types
pub type NodeType = String;

/// Enum of AudioNode::ChannelCountMode from the spec
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ChannelCountMode {
    /// `clamped-max`
    #[serde(rename = "clamped-max")]
    ClampedMax,
    /// `explicit`
    #[serde(rename = "explicit")]
    Explicit,
    /// `max`
    #[serde(rename = "max")]
    Max,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Enum of AudioNode::ChannelInterpretation from the spec
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ChannelInterpretation {
    /// `discrete`
    #[serde(rename = "discrete")]
    Discrete,
    /// `speakers`
    #[serde(rename = "speakers")]
    Speakers,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Enum of AudioParam types
pub type ParamType = String;

/// Enum of AudioParam::AutomationRate from the spec
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AutomationRate {
    /// `a-rate`
    #[serde(rename = "a-rate")]
    ARate,
    /// `k-rate`
    #[serde(rename = "k-rate")]
    KRate,
    /// A value this vendored schema does not list. Chrome adds values ahead of
    /// the published protocol, so an unrecognised one is kept as it arrived
    /// rather than failing the payload it came in.
    #[serde(untagged)]
    Unrecognized(String),
}

/// Fields in AudioContext that change in real-time.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ContextRealtimeData {
    /// The current context time in second in BaseAudioContext.
    #[serde(rename = "currentTime")]
    pub current_time: f64,
    /// The time spent on rendering graph divided by render quantum duration, and
    /// multiplied by 100. 100 means the audio renderer reached the full capacity
    /// and glitch may occur.
    #[serde(rename = "renderCapacity")]
    pub render_capacity: f64,
    /// A running mean of callback interval.
    #[serde(rename = "callbackIntervalMean")]
    pub callback_interval_mean: f64,
    /// A running variance of callback interval.
    #[serde(rename = "callbackIntervalVariance")]
    pub callback_interval_variance: f64,
}

/// Protocol object for BaseAudioContext
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BaseAudioContext {
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
    #[serde(rename = "contextType")]
    pub context_type: ContextType,
    #[serde(rename = "contextState")]
    pub context_state: ContextState,
    #[serde(
        rename = "realtimeData",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub realtime_data: Option<ContextRealtimeData>,
    /// Platform-dependent callback buffer size.
    #[serde(rename = "callbackBufferSize")]
    pub callback_buffer_size: f64,
    /// Number of output channels supported by audio hardware in use.
    #[serde(rename = "maxOutputChannelCount")]
    pub max_output_channel_count: f64,
    /// Context sample rate.
    #[serde(rename = "sampleRate")]
    pub sample_rate: f64,
}

/// Protocol object for AudioListener
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AudioListener {
    #[serde(rename = "listenerId")]
    pub listener_id: GraphObjectId,
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
}

/// Protocol object for AudioNode
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AudioNode {
    #[serde(rename = "nodeId")]
    pub node_id: GraphObjectId,
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
    #[serde(rename = "nodeType")]
    pub node_type: NodeType,
    #[serde(rename = "numberOfInputs")]
    pub number_of_inputs: f64,
    #[serde(rename = "numberOfOutputs")]
    pub number_of_outputs: f64,
    #[serde(rename = "channelCount")]
    pub channel_count: f64,
    #[serde(rename = "channelCountMode")]
    pub channel_count_mode: ChannelCountMode,
    #[serde(rename = "channelInterpretation")]
    pub channel_interpretation: ChannelInterpretation,
}

/// Protocol object for AudioParam
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AudioParam {
    #[serde(rename = "paramId")]
    pub param_id: GraphObjectId,
    #[serde(rename = "nodeId")]
    pub node_id: GraphObjectId,
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
    #[serde(rename = "paramType")]
    pub param_type: ParamType,
    pub rate: AutomationRate,
    #[serde(rename = "defaultValue")]
    pub default_value: f64,
    #[serde(rename = "minValue")]
    pub min_value: f64,
    #[serde(rename = "maxValue")]
    pub max_value: f64,
}

/// Enables the WebAudio domain and starts sending context lifetime events.
///
/// Parameters of `WebAudio.enable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnableParams {}

impl crate::typed::Command for EnableParams {
    const METHOD: &'static str = "WebAudio.enable";
    type Returns = crate::typed::NoReturns;
}

/// Disables the WebAudio domain.
///
/// Parameters of `WebAudio.disable`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DisableParams {}

impl crate::typed::Command for DisableParams {
    const METHOD: &'static str = "WebAudio.disable";
    type Returns = crate::typed::NoReturns;
}

/// Fetch the realtime data from the registered contexts.
///
/// Parameters of `WebAudio.getRealtimeData`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetRealtimeDataParams {
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
}

/// What `WebAudio.getRealtimeData` answers with.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GetRealtimeDataReturns {
    #[serde(rename = "realtimeData")]
    pub realtime_data: ContextRealtimeData,
}

impl crate::typed::Command for GetRealtimeDataParams {
    const METHOD: &'static str = "WebAudio.getRealtimeData";
    type Returns = GetRealtimeDataReturns;
}

/// Notifies that a new BaseAudioContext has been created.
///
/// Payload of the `WebAudio.contextCreated` event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContextCreatedEvent {
    pub context: BaseAudioContext,
}

impl crate::typed::Event for ContextCreatedEvent {
    const METHOD: &'static str = "WebAudio.contextCreated";
}

/// Notifies that an existing BaseAudioContext will be destroyed.
///
/// Payload of the `WebAudio.contextWillBeDestroyed` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ContextWillBeDestroyedEvent {
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
}

impl crate::typed::Event for ContextWillBeDestroyedEvent {
    const METHOD: &'static str = "WebAudio.contextWillBeDestroyed";
}

/// Notifies that existing BaseAudioContext has changed some properties (id
/// stays the same)..
///
/// Payload of the `WebAudio.contextChanged` event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContextChangedEvent {
    pub context: BaseAudioContext,
}

impl crate::typed::Event for ContextChangedEvent {
    const METHOD: &'static str = "WebAudio.contextChanged";
}

/// Notifies that the construction of an AudioListener has finished.
///
/// Payload of the `WebAudio.audioListenerCreated` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AudioListenerCreatedEvent {
    pub listener: AudioListener,
}

impl crate::typed::Event for AudioListenerCreatedEvent {
    const METHOD: &'static str = "WebAudio.audioListenerCreated";
}

/// Notifies that a new AudioListener has been created.
///
/// Payload of the `WebAudio.audioListenerWillBeDestroyed` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AudioListenerWillBeDestroyedEvent {
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
    #[serde(rename = "listenerId")]
    pub listener_id: GraphObjectId,
}

impl crate::typed::Event for AudioListenerWillBeDestroyedEvent {
    const METHOD: &'static str = "WebAudio.audioListenerWillBeDestroyed";
}

/// Notifies that a new AudioNode has been created.
///
/// Payload of the `WebAudio.audioNodeCreated` event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AudioNodeCreatedEvent {
    pub node: AudioNode,
}

impl crate::typed::Event for AudioNodeCreatedEvent {
    const METHOD: &'static str = "WebAudio.audioNodeCreated";
}

/// Notifies that an existing AudioNode has been destroyed.
///
/// Payload of the `WebAudio.audioNodeWillBeDestroyed` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AudioNodeWillBeDestroyedEvent {
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
    #[serde(rename = "nodeId")]
    pub node_id: GraphObjectId,
}

impl crate::typed::Event for AudioNodeWillBeDestroyedEvent {
    const METHOD: &'static str = "WebAudio.audioNodeWillBeDestroyed";
}

/// Notifies that a new AudioParam has been created.
///
/// Payload of the `WebAudio.audioParamCreated` event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AudioParamCreatedEvent {
    pub param: AudioParam,
}

impl crate::typed::Event for AudioParamCreatedEvent {
    const METHOD: &'static str = "WebAudio.audioParamCreated";
}

/// Notifies that an existing AudioParam has been destroyed.
///
/// Payload of the `WebAudio.audioParamWillBeDestroyed` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AudioParamWillBeDestroyedEvent {
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
    #[serde(rename = "nodeId")]
    pub node_id: GraphObjectId,
    #[serde(rename = "paramId")]
    pub param_id: GraphObjectId,
}

impl crate::typed::Event for AudioParamWillBeDestroyedEvent {
    const METHOD: &'static str = "WebAudio.audioParamWillBeDestroyed";
}

/// Notifies that two AudioNodes are connected.
///
/// Payload of the `WebAudio.nodesConnected` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct NodesConnectedEvent {
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
    #[serde(rename = "sourceId")]
    pub source_id: GraphObjectId,
    #[serde(rename = "destinationId")]
    pub destination_id: GraphObjectId,
    #[serde(
        rename = "sourceOutputIndex",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_output_index: Option<f64>,
    #[serde(
        rename = "destinationInputIndex",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub destination_input_index: Option<f64>,
}

impl crate::typed::Event for NodesConnectedEvent {
    const METHOD: &'static str = "WebAudio.nodesConnected";
}

/// Notifies that AudioNodes are disconnected. The destination can be null,
/// and it means all the outgoing connections from the source are
/// disconnected.
///
/// Payload of the `WebAudio.nodesDisconnected` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct NodesDisconnectedEvent {
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
    #[serde(rename = "sourceId")]
    pub source_id: GraphObjectId,
    #[serde(rename = "destinationId")]
    pub destination_id: GraphObjectId,
    #[serde(
        rename = "sourceOutputIndex",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_output_index: Option<f64>,
    #[serde(
        rename = "destinationInputIndex",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub destination_input_index: Option<f64>,
}

impl crate::typed::Event for NodesDisconnectedEvent {
    const METHOD: &'static str = "WebAudio.nodesDisconnected";
}

/// Notifies that an AudioNode is connected to an AudioParam.
///
/// Payload of the `WebAudio.nodeParamConnected` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct NodeParamConnectedEvent {
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
    #[serde(rename = "sourceId")]
    pub source_id: GraphObjectId,
    #[serde(rename = "destinationId")]
    pub destination_id: GraphObjectId,
    #[serde(
        rename = "sourceOutputIndex",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_output_index: Option<f64>,
}

impl crate::typed::Event for NodeParamConnectedEvent {
    const METHOD: &'static str = "WebAudio.nodeParamConnected";
}

/// Notifies that an AudioNode is disconnected to an AudioParam.
///
/// Payload of the `WebAudio.nodeParamDisconnected` event.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct NodeParamDisconnectedEvent {
    #[serde(rename = "contextId")]
    pub context_id: GraphObjectId,
    #[serde(rename = "sourceId")]
    pub source_id: GraphObjectId,
    #[serde(rename = "destinationId")]
    pub destination_id: GraphObjectId,
    #[serde(
        rename = "sourceOutputIndex",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_output_index: Option<f64>,
}

impl crate::typed::Event for NodeParamDisconnectedEvent {
    const METHOD: &'static str = "WebAudio.nodeParamDisconnected";
}
