//! Rendering schema domains as Rust source.

use std::collections::BTreeMap;

use crate::docs::{defuse, wrap};
use crate::names::screaming_snake;
use crate::schema::{Command, Domain};

/// Stamped onto every generated file so nobody edits one by hand.
const BANNER: &str = "// @generated by `just generate-methods` from protocol/*.json.\n\
                      // Do not edit by hand; edit xtask/ and regenerate.\n";

/// The worked example that opens the index module.
const INDEX_EXAMPLE: &str = "\
//! ```no_run
//! # use cdp_driver::CdpClient;
//! use cdp_driver::methods::target;
//! # use serde_json::json;
//!
//! # async fn run(client: &CdpClient) -> cdp_driver::Result<()> {
//! let created = client
//!     .call_raw(target::CREATE_TARGET, json!({ \"url\": \"about:blank\" }))
//!     .await?;
//! # Ok(())
//! # }
//! ```
";

/// Render a single command as a doc-commented `pub const`.
fn command(domain: &str, command: &Command) -> String {
    let mut out: Vec<String> = Vec::new();

    match &command.description {
        Some(text) => out.extend(wrap(&defuse(text), "///")),
        None => out.push(format!("/// `{}.{}`", domain, command.name)),
    }

    if command.deprecated || command.experimental {
        out.push("///".to_string());
        if command.deprecated {
            out.push("/// Deprecated in the protocol.".to_string());
        }
        if command.experimental {
            out.push("/// Experimental: may change without notice.".to_string());
        }
    }

    if !command.parameters.is_empty() {
        out.push("///".to_string());
        out.push("/// Parameters:".to_string());
        for field in &command.parameters {
            let optional = if field.optional { " (optional)" } else { "" };
            out.push(format!(
                "/// - `{}`: {}{}",
                field.name,
                defuse(&field.type_name()),
                optional
            ));
        }
    }

    if !command.returns.is_empty() {
        out.push("///".to_string());
        let names: Vec<String> = command
            .returns
            .iter()
            .map(|field| format!("`{}`", field.name))
            .collect();
        out.push(format!("/// Returns: {}", names.join(", ")));
    }

    out.push(format!(
        "pub const {}: &str = \"{}.{}\";",
        screaming_snake(&command.name),
        domain,
        command.name
    ));

    out.join("\n")
}

/// Render every command of one domain as that domain's module.
pub fn domain(domain: &Domain) -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push('\n');

    match &domain.description {
        Some(text) => {
            out.push_str(&wrap(&defuse(text), "//!").join("\n"));
            out.push('\n');
        }
        None => out.push_str(&format!("//! The `{}` domain.\n", domain.domain)),
    }
    out.push_str(&format!(
        "//!\n//! Method names for the `{}` domain, for use with\n\
         //! [`CdpClient::call`](crate::CdpClient::call).\n",
        domain.domain
    ));
    if domain.deprecated {
        out.push_str("//!\n//! This domain is deprecated in the protocol.\n");
    }
    if domain.experimental {
        out.push_str("//!\n//! This domain is experimental and may change without notice.\n");
    }

    for each in &domain.commands {
        out.push('\n');
        out.push_str(&command(&domain.domain, each));
        out.push('\n');
    }
    out
}

/// Render the parent module that publishes every domain module.
pub fn index(modules: &BTreeMap<String, String>) -> String {
    let mut out = String::new();
    out.push_str(BANNER);
    out.push_str(
        "\n//! CDP method names, one module per protocol domain.\n\
         //!\n\
         //! [`CdpClient::call`](crate::CdpClient::call) takes a method name as a\n\
         //! string. These constants let the editor complete that name and the\n\
         //! compiler reject a typo, and each one carries the protocol's own\n\
         //! description, parameters and return fields as documentation.\n\
         //!\n",
    );
    out.push_str(INDEX_EXAMPLE);
    out.push('\n');
    for module in modules.keys() {
        out.push_str(&format!("pub mod {module};\n"));
    }
    out
}
