// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! A domain for ad-related metrics and data.
//!
//! Method names for the `Ads` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is experimental and may change without notice.

/// Retrieves ad metrics for the current page.
///
/// Returns: `metrics`
pub const GET_AD_METRICS: &str = "Ads.getAdMetrics";
