// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! Defines commands and events for Autofill.
//!
//! Method names for the `Autofill` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is experimental and may change without notice.

/// Trigger autofill on a form identified by the fieldId. If the field and
/// related form cannot be autofilled, returns an error.
///
/// Parameters:
/// - `fieldId`: DOM.BackendNodeId
/// - `frameId`: Page.FrameId (optional)
/// - `card`: CreditCard (optional)
/// - `address`: Address (optional)
pub const TRIGGER: &str = "Autofill.trigger";

/// Set addresses so that developers can verify their forms implementation.
///
/// Parameters:
/// - `addresses`: array
pub const SET_ADDRESSES: &str = "Autofill.setAddresses";

/// Disables autofill domain notifications.
pub const DISABLE: &str = "Autofill.disable";

/// Enables autofill domain notifications.
pub const ENABLE: &str = "Autofill.enable";
