// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! This domain is deprecated - use Runtime or Log instead.
//!
//! Method names for the `Console` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is deprecated in the protocol.

/// Does nothing.
pub const CLEAR_MESSAGES: &str = "Console.clearMessages";

/// Disables console domain, prevents further console messages from being
/// reported to the client.
pub const DISABLE: &str = "Console.disable";

/// Enables console domain, sends the messages collected so far to the client
/// by means of the `messageAdded` notification.
pub const ENABLE: &str = "Console.enable";
