// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! This domain exposes the current state of the CrashReportContext API.
//!
//! Method names for the `CrashReportContext` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is experimental and may change without notice.

/// Returns all entries in the CrashReportContext across all frames in the
/// page.
///
/// Returns: `entries`
pub const GET_ENTRIES: &str = "CrashReportContext.getEntries";
