// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! The `DeviceAccess` domain.
//!
//! Method names for the `DeviceAccess` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is experimental and may change without notice.

/// Enable events in this domain.
pub const ENABLE: &str = "DeviceAccess.enable";

/// Disable events in this domain.
pub const DISABLE: &str = "DeviceAccess.disable";

/// Select a device in response to a DeviceAccess.deviceRequestPrompted event.
///
/// Parameters:
/// - `id`: RequestId
/// - `deviceId`: DeviceId
pub const SELECT_PROMPT: &str = "DeviceAccess.selectPrompt";

/// Cancel a prompt in response to a DeviceAccess.deviceRequestPrompted event.
///
/// Parameters:
/// - `id`: RequestId
pub const CANCEL_PROMPT: &str = "DeviceAccess.cancelPrompt";
