// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! This domain exposes DOM read/write operations. Each DOM Node is
//! represented with its mirror object that has an `id`. This `id` can be used
//! to get additional information on the Node, resolve it into the JavaScript
//! object wrapper, etc. It is important that client receives DOM events only
//! for the nodes that are known to the client. Backend keeps track of the
//! nodes that were sent to the client and never sends the same node twice. It
//! is client's responsibility to collect information about the nodes that
//! were sent to the client. Note that `iframe` owner elements will return
//! corresponding document elements as their child nodes.
//!
//! Method names for the `DOM` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).

/// Collects class names for the node with given id and all of it's child
/// nodes.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
///
/// Returns: `classNames`
pub const COLLECT_CLASS_NAMES_FROM_SUBTREE: &str = "DOM.collectClassNamesFromSubtree";

/// Creates a deep copy of the specified node and places it into the target
/// container before the given anchor.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `targetNodeId`: NodeId
/// - `insertBeforeNodeId`: NodeId (optional)
///
/// Returns: `nodeId`
pub const COPY_TO: &str = "DOM.copyTo";

/// Describes node given its id, does not require domain to be enabled. Does
/// not start tracking any objects, can be used for automation.
///
/// Parameters:
/// - `nodeId`: NodeId (optional)
/// - `backendNodeId`: BackendNodeId (optional)
/// - `objectId`: Runtime.RemoteObjectId (optional)
/// - `depth`: integer (optional)
/// - `pierce`: boolean (optional)
///
/// Returns: `node`
pub const DESCRIBE_NODE: &str = "DOM.describeNode";

/// Scrolls the specified rect of the given node into view if not already
/// visible. Note: exactly one between nodeId, backendNodeId and objectId
/// should be passed to identify the node.
///
/// Parameters:
/// - `nodeId`: NodeId (optional)
/// - `backendNodeId`: BackendNodeId (optional)
/// - `objectId`: Runtime.RemoteObjectId (optional)
/// - `rect`: Rect (optional)
pub const SCROLL_INTO_VIEW_IF_NEEDED: &str = "DOM.scrollIntoViewIfNeeded";

/// Disables DOM agent for the given page.
pub const DISABLE: &str = "DOM.disable";

/// Discards search results from the session with the given id.
/// `getSearchResults` should no longer be called for that search.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `searchId`: string
pub const DISCARD_SEARCH_RESULTS: &str = "DOM.discardSearchResults";

/// Enables DOM agent for the given page.
///
/// Parameters:
/// - `includeWhitespace`: string (optional)
pub const ENABLE: &str = "DOM.enable";

/// Focuses the given element.
///
/// Parameters:
/// - `nodeId`: NodeId (optional)
/// - `backendNodeId`: BackendNodeId (optional)
/// - `objectId`: Runtime.RemoteObjectId (optional)
pub const FOCUS: &str = "DOM.focus";

/// Returns attributes for the specified node.
///
/// Parameters:
/// - `nodeId`: NodeId
///
/// Returns: `attributes`
pub const GET_ATTRIBUTES: &str = "DOM.getAttributes";

/// Returns boxes for the given node.
///
/// Parameters:
/// - `nodeId`: NodeId (optional)
/// - `backendNodeId`: BackendNodeId (optional)
/// - `objectId`: Runtime.RemoteObjectId (optional)
///
/// Returns: `model`
pub const GET_BOX_MODEL: &str = "DOM.getBoxModel";

/// Returns quads that describe node position on the page. This method might
/// return multiple quads for inline nodes.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId (optional)
/// - `backendNodeId`: BackendNodeId (optional)
/// - `objectId`: Runtime.RemoteObjectId (optional)
///
/// Returns: `quads`
pub const GET_CONTENT_QUADS: &str = "DOM.getContentQuads";

/// Returns the root DOM node (and optionally the subtree) to the caller.
/// Implicitly enables the DOM domain events for the current target.
///
/// Parameters:
/// - `depth`: integer (optional)
/// - `pierce`: boolean (optional)
///
/// Returns: `root`
pub const GET_DOCUMENT: &str = "DOM.getDocument";

/// Returns the root DOM node (and optionally the subtree) to the caller.
/// Deprecated, as it is not designed to work well with the rest of the DOM
/// agent. Use DOMSnapshot.captureSnapshot instead.
///
/// Deprecated in the protocol.
///
/// Parameters:
/// - `depth`: integer (optional)
/// - `pierce`: boolean (optional)
///
/// Returns: `nodes`
pub const GET_FLATTENED_DOCUMENT: &str = "DOM.getFlattenedDocument";

/// Finds nodes with a given computed style in a subtree.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `computedStyles`: array
/// - `pierce`: boolean (optional)
///
/// Returns: `nodeIds`
pub const GET_NODES_FOR_SUBTREE_BY_STYLE: &str = "DOM.getNodesForSubtreeByStyle";

/// Returns node id at given location. Depending on whether DOM domain is
/// enabled, nodeId is either returned or not.
///
/// Parameters:
/// - `x`: integer
/// - `y`: integer
/// - `includeUserAgentShadowDOM`: boolean (optional)
/// - `ignorePointerEventsNone`: boolean (optional)
///
/// Returns: `backendNodeId`, `frameId`, `nodeId`
pub const GET_NODE_FOR_LOCATION: &str = "DOM.getNodeForLocation";

/// Returns node's HTML markup.
///
/// Parameters:
/// - `nodeId`: NodeId (optional)
/// - `backendNodeId`: BackendNodeId (optional)
/// - `objectId`: Runtime.RemoteObjectId (optional)
/// - `includeShadowDOM`: boolean (optional)
///
/// Returns: `outerHTML`
pub const GET_OUTER_HTML: &str = "DOM.getOuterHTML";

/// Returns the id of the nearest ancestor that is a relayout boundary.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
///
/// Returns: `nodeId`
pub const GET_RELAYOUT_BOUNDARY: &str = "DOM.getRelayoutBoundary";

/// Returns search results from given `fromIndex` to given `toIndex` from the
/// search with the given identifier.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `searchId`: string
/// - `fromIndex`: integer
/// - `toIndex`: integer
///
/// Returns: `nodeIds`
pub const GET_SEARCH_RESULTS: &str = "DOM.getSearchResults";

/// Hides any highlight.
pub const HIDE_HIGHLIGHT: &str = "DOM.hideHighlight";

/// Highlights DOM node.
pub const HIGHLIGHT_NODE: &str = "DOM.highlightNode";

/// Highlights given rectangle.
pub const HIGHLIGHT_RECT: &str = "DOM.highlightRect";

/// Marks last undoable state.
///
/// Experimental: may change without notice.
pub const MARK_UNDOABLE_STATE: &str = "DOM.markUndoableState";

/// Moves node into the new container, places it before the given anchor.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `targetNodeId`: NodeId
/// - `insertBeforeNodeId`: NodeId (optional)
///
/// Returns: `nodeId`
pub const MOVE_TO: &str = "DOM.moveTo";

/// Searches for a given string in the DOM tree. Use `getSearchResults` to
/// access search results or `cancelSearch` to end this search session.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `query`: string
/// - `includeUserAgentShadowDOM`: boolean (optional)
///
/// Returns: `searchId`, `resultCount`
pub const PERFORM_SEARCH: &str = "DOM.performSearch";

/// Requests that the node is sent to the caller given its path. // FIXME, use
/// XPath
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `path`: string
///
/// Returns: `nodeId`
pub const PUSH_NODE_BY_PATH_TO_FRONTEND: &str = "DOM.pushNodeByPathToFrontend";

/// Requests that a batch of nodes is sent to the caller given their backend
/// node ids.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `backendNodeIds`: array
///
/// Returns: `nodeIds`
pub const PUSH_NODES_BY_BACKEND_IDS_TO_FRONTEND: &str = "DOM.pushNodesByBackendIdsToFrontend";

/// Executes `querySelector` on a given node.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `selector`: string
///
/// Returns: `nodeId`
pub const QUERY_SELECTOR: &str = "DOM.querySelector";

/// Executes `querySelectorAll` on a given node.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `selector`: string
///
/// Returns: `nodeIds`
pub const QUERY_SELECTOR_ALL: &str = "DOM.querySelectorAll";

/// Returns NodeIds of current top layer elements. Top layer is rendered
/// closest to the user within a viewport, therefore its elements always
/// appear on top of all other content.
///
/// Experimental: may change without notice.
///
/// Returns: `nodeIds`
pub const GET_TOP_LAYER_ELEMENTS: &str = "DOM.getTopLayerElements";

/// Returns the NodeId of the matched element according to certain relations.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `relation`: string
///
/// Returns: `nodeId`
pub const GET_ELEMENT_BY_RELATION: &str = "DOM.getElementByRelation";

/// Re-does the last undone action.
///
/// Experimental: may change without notice.
pub const REDO: &str = "DOM.redo";

/// Removes attribute with given name from an element with given id.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `name`: string
pub const REMOVE_ATTRIBUTE: &str = "DOM.removeAttribute";

/// Removes node with given id.
///
/// Parameters:
/// - `nodeId`: NodeId
pub const REMOVE_NODE: &str = "DOM.removeNode";

/// Requests that children of the node with given id are returned to the
/// caller in form of `setChildNodes` events where not only immediate children
/// are retrieved, but all children down to the specified depth.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `depth`: integer (optional)
/// - `pierce`: boolean (optional)
pub const REQUEST_CHILD_NODES: &str = "DOM.requestChildNodes";

/// Requests that the node is sent to the caller given the JavaScript node
/// object reference. All nodes that form the path from the node to the root
/// are also sent to the client as a series of `setChildNodes` notifications.
///
/// Parameters:
/// - `objectId`: Runtime.RemoteObjectId
///
/// Returns: `nodeId`
pub const REQUEST_NODE: &str = "DOM.requestNode";

/// Resolves the JavaScript node object for a given NodeId or BackendNodeId.
///
/// Parameters:
/// - `nodeId`: NodeId (optional)
/// - `backendNodeId`: DOM.BackendNodeId (optional)
/// - `objectGroup`: string (optional)
/// - `executionContextId`: Runtime.ExecutionContextId (optional)
///
/// Returns: `object`
pub const RESOLVE_NODE: &str = "DOM.resolveNode";

/// Sets attribute for an element with given id.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `name`: string
/// - `value`: string
pub const SET_ATTRIBUTE_VALUE: &str = "DOM.setAttributeValue";

/// Sets attributes on element with given id. This method is useful when user
/// edits some existing attribute value and types in several attribute
/// name/value pairs.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `text`: string
/// - `name`: string (optional)
pub const SET_ATTRIBUTES_AS_TEXT: &str = "DOM.setAttributesAsText";

/// Sets files for the given file input element.
///
/// Parameters:
/// - `files`: array
/// - `nodeId`: NodeId (optional)
/// - `backendNodeId`: BackendNodeId (optional)
/// - `objectId`: Runtime.RemoteObjectId (optional)
pub const SET_FILE_INPUT_FILES: &str = "DOM.setFileInputFiles";

/// Sets if stack traces should be captured for Nodes. See
/// `Node.getNodeStackTraces`. Default is disabled.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `enable`: boolean
pub const SET_NODE_STACK_TRACES_ENABLED: &str = "DOM.setNodeStackTracesEnabled";

/// Gets stack traces associated with a Node. As of now, only provides stack
/// trace for Node creation.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
///
/// Returns: `creation`
pub const GET_NODE_STACK_TRACES: &str = "DOM.getNodeStackTraces";

/// Returns file information for the given File wrapper.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `objectId`: Runtime.RemoteObjectId
///
/// Returns: `path`
pub const GET_FILE_INFO: &str = "DOM.getFileInfo";

/// Returns list of detached nodes
///
/// Experimental: may change without notice.
///
/// Returns: `detachedNodes`
pub const GET_DETACHED_DOM_NODES: &str = "DOM.getDetachedDomNodes";

/// Enables console to refer to the node with given id via $x (see Command
/// Line API for more details $x functions).
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
pub const SET_INSPECTED_NODE: &str = "DOM.setInspectedNode";

/// Sets node name for a node with given id.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `name`: string
///
/// Returns: `nodeId`
pub const SET_NODE_NAME: &str = "DOM.setNodeName";

/// Sets node value for a node with given id.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `value`: string
pub const SET_NODE_VALUE: &str = "DOM.setNodeValue";

/// Sets node HTML markup, returns new node id.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `outerHTML`: string
pub const SET_OUTER_HTML: &str = "DOM.setOuterHTML";

/// Undoes the last performed action.
///
/// Experimental: may change without notice.
pub const UNDO: &str = "DOM.undo";

/// Returns iframe node that owns iframe with the given domain.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `frameId`: Page.FrameId
///
/// Returns: `backendNodeId`, `nodeId`
pub const GET_FRAME_OWNER: &str = "DOM.getFrameOwner";

/// Returns the query container of the given node based on container query
/// conditions: containerName, physical and logical axes, and whether it
/// queries scroll-state or anchored elements. If no axes are provided and
/// queriesScrollState is false, the style container is returned, which is the
/// direct parent or the closest element with a matching container-name.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `containerName`: string (optional)
/// - `physicalAxes`: PhysicalAxes (optional)
/// - `logicalAxes`: LogicalAxes (optional)
/// - `queriesScrollState`: boolean (optional)
/// - `queriesAnchored`: boolean (optional)
///
/// Returns: `nodeId`
pub const GET_CONTAINER_FOR_NODE: &str = "DOM.getContainerForNode";

/// Returns the descendants of a container query container that have container
/// queries against this container.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
///
/// Returns: `nodeIds`
pub const GET_QUERYING_DESCENDANTS_FOR_CONTAINER: &str = "DOM.getQueryingDescendantsForContainer";

/// Returns the target anchor element of the given anchor query according to
/// <https://www.w3.org/TR/css-anchor-position-1/#target>.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `anchorSpecifier`: string (optional)
///
/// Returns: `nodeId`
pub const GET_ANCHOR_ELEMENT: &str = "DOM.getAnchorElement";

/// When enabling, this API force-opens the popover identified by nodeId and
/// keeps it open until disabled.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `enable`: boolean
/// - `invokerNodeId`: BackendNodeId (optional)
///
/// Returns: `nodeIds`
pub const FORCE_SHOW_POPOVER: &str = "DOM.forceShowPopover";

/// When enabling, this API forces an element to gain interest in its target,
/// keeping interest active until disabled.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `nodeId`: NodeId
/// - `enable`: boolean
pub const FORCE_SHOW_INTEREST: &str = "DOM.forceShowInterest";
