// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! Query and modify DOM storage.
//!
//! Method names for the `DOMStorage` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is experimental and may change without notice.

/// `DOMStorage.clear`
///
/// Parameters:
/// - `storageId`: StorageId
pub const CLEAR: &str = "DOMStorage.clear";

/// Disables storage tracking, prevents storage events from being sent to the
/// client.
pub const DISABLE: &str = "DOMStorage.disable";

/// Enables storage tracking, storage events will now be delivered to the
/// client.
pub const ENABLE: &str = "DOMStorage.enable";

/// `DOMStorage.getDOMStorageItems`
///
/// Parameters:
/// - `storageId`: StorageId
///
/// Returns: `entries`
pub const GET_DOM_STORAGE_ITEMS: &str = "DOMStorage.getDOMStorageItems";

/// `DOMStorage.removeDOMStorageItem`
///
/// Parameters:
/// - `storageId`: StorageId
/// - `key`: string
pub const REMOVE_DOM_STORAGE_ITEM: &str = "DOMStorage.removeDOMStorageItem";

/// `DOMStorage.setDOMStorageItem`
///
/// Parameters:
/// - `storageId`: StorageId
/// - `key`: string
/// - `value`: string
pub const SET_DOM_STORAGE_ITEM: &str = "DOMStorage.setDOMStorageItem";
