// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! EventBreakpoints permits setting JavaScript breakpoints on operations and
//! events occurring in native code invoked from JavaScript. Once breakpoint
//! is hit, it is reported through Debugger domain, similarly to regular
//! breakpoints being hit.
//!
//! Method names for the `EventBreakpoints` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is experimental and may change without notice.

/// Sets breakpoint on particular native event.
///
/// Parameters:
/// - `eventName`: string
pub const SET_INSTRUMENTATION_BREAKPOINT: &str = "EventBreakpoints.setInstrumentationBreakpoint";

/// Removes breakpoint on particular native event.
///
/// Parameters:
/// - `eventName`: string
pub const REMOVE_INSTRUMENTATION_BREAKPOINT: &str =
    "EventBreakpoints.removeInstrumentationBreakpoint";

/// Removes all breakpoints
pub const DISABLE: &str = "EventBreakpoints.disable";
