// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! The `FileSystem` domain.
//!
//! Method names for the `FileSystem` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is experimental and may change without notice.

/// `FileSystem.getDirectory`
///
/// Parameters:
/// - `bucketFileSystemLocator`: BucketFileSystemLocator
///
/// Returns: `directory`
pub const GET_DIRECTORY: &str = "FileSystem.getDirectory";
