// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! Actions and events related to the inspected page belong to the page
//! domain.
//!
//! Method names for the `Page` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).

/// Deprecated, please use addScriptToEvaluateOnNewDocument instead.
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
///
/// Parameters:
/// - `scriptSource`: string
///
/// Returns: `identifier`
pub const ADD_SCRIPT_TO_EVALUATE_ON_LOAD: &str = "Page.addScriptToEvaluateOnLoad";

/// Evaluates given script in every frame upon creation (before loading
/// frame's scripts).
///
/// Parameters:
/// - `source`: string
/// - `worldName`: string (optional)
/// - `includeCommandLineAPI`: boolean (optional)
/// - `runImmediately`: boolean (optional)
///
/// Returns: `identifier`
pub const ADD_SCRIPT_TO_EVALUATE_ON_NEW_DOCUMENT: &str = "Page.addScriptToEvaluateOnNewDocument";

/// Brings page to front (activates tab).
pub const BRING_TO_FRONT: &str = "Page.bringToFront";

/// Capture page screenshot.
///
/// Parameters:
/// - `format`: string (optional)
/// - `quality`: integer (optional)
/// - `clip`: Viewport (optional)
/// - `fromSurface`: boolean (optional)
/// - `captureBeyondViewport`: boolean (optional)
/// - `optimizeForSpeed`: boolean (optional)
///
/// Returns: `data`
pub const CAPTURE_SCREENSHOT: &str = "Page.captureScreenshot";

/// Returns a snapshot of the page as a string. For MHTML format, the
/// serialization includes iframes, shadow DOM, external resources, and
/// element-inline styles.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `format`: string (optional)
///
/// Returns: `data`
pub const CAPTURE_SNAPSHOT: &str = "Page.captureSnapshot";

/// Clears the overridden device metrics.
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
pub const CLEAR_DEVICE_METRICS_OVERRIDE: &str = "Page.clearDeviceMetricsOverride";

/// Clears the overridden Device Orientation.
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
pub const CLEAR_DEVICE_ORIENTATION_OVERRIDE: &str = "Page.clearDeviceOrientationOverride";

/// Clears the overridden Geolocation Position and Error.
///
/// Deprecated in the protocol.
pub const CLEAR_GEOLOCATION_OVERRIDE: &str = "Page.clearGeolocationOverride";

/// Creates an isolated world for the given frame.
///
/// Parameters:
/// - `frameId`: FrameId
/// - `worldName`: string (optional)
/// - `grantUniveralAccess`: boolean (optional)
/// - `contentSecurityPolicy`: string (optional)
///
/// Returns: `executionContextId`
pub const CREATE_ISOLATED_WORLD: &str = "Page.createIsolatedWorld";

/// Deletes browser cookie with given name, domain and path.
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
///
/// Parameters:
/// - `cookieName`: string
/// - `url`: string
pub const DELETE_COOKIE: &str = "Page.deleteCookie";

/// Disables page domain notifications.
pub const DISABLE: &str = "Page.disable";

/// Enables page domain notifications.
///
/// Parameters:
/// - `enableFileChooserOpenedEvent`: boolean (optional)
pub const ENABLE: &str = "Page.enable";

/// Gets the processed manifest for this current document. This API always
/// waits for the manifest to be loaded. If manifestId is provided, and it
/// does not match the manifest of the current document, this API errors out.
/// If there is not a loaded page, this API errors out immediately.
///
/// Parameters:
/// - `manifestId`: string (optional)
///
/// Returns: `url`, `errors`, `data`, `parsed`, `manifest`
pub const GET_APP_MANIFEST: &str = "Page.getAppManifest";

/// `Page.getInstallabilityErrors`
///
/// Experimental: may change without notice.
///
/// Returns: `installabilityErrors`
pub const GET_INSTALLABILITY_ERRORS: &str = "Page.getInstallabilityErrors";

/// Deprecated because it's not guaranteed that the returned icon is in fact
/// the one used for PWA installation.
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
///
/// Returns: `primaryIcon`
pub const GET_MANIFEST_ICONS: &str = "Page.getManifestIcons";

/// Returns the unique (PWA) app id. Only returns values if the feature flag
/// 'WebAppEnableManifestId' is enabled
///
/// Experimental: may change without notice.
///
/// Returns: `appId`, `recommendedId`
pub const GET_APP_ID: &str = "Page.getAppId";

/// `Page.getAdScriptAncestry`
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `frameId`: FrameId
///
/// Returns: `adScriptAncestry`
pub const GET_AD_SCRIPT_ANCESTRY: &str = "Page.getAdScriptAncestry";

/// Returns present frame tree structure.
///
/// Returns: `frameTree`
pub const GET_FRAME_TREE: &str = "Page.getFrameTree";

/// Returns metrics relating to the layouting of the page, such as viewport
/// bounds/scale.
///
/// Returns: `layoutViewport`, `visualViewport`, `contentSize`, `cssLayoutViewport`, `cssVisualViewport`, `cssContentSize`
pub const GET_LAYOUT_METRICS: &str = "Page.getLayoutMetrics";

/// Returns navigation history for the current page.
///
/// Returns: `currentIndex`, `entries`
pub const GET_NAVIGATION_HISTORY: &str = "Page.getNavigationHistory";

/// Resets navigation history for the current page.
pub const RESET_NAVIGATION_HISTORY: &str = "Page.resetNavigationHistory";

/// Returns content of the given resource.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `frameId`: FrameId
/// - `url`: string
///
/// Returns: `content`, `base64Encoded`
pub const GET_RESOURCE_CONTENT: &str = "Page.getResourceContent";

/// Returns present frame / resource tree structure.
///
/// Experimental: may change without notice.
///
/// Returns: `frameTree`
pub const GET_RESOURCE_TREE: &str = "Page.getResourceTree";

/// Accepts or dismisses a JavaScript initiated dialog (alert, confirm,
/// prompt, or onbeforeunload).
///
/// Parameters:
/// - `accept`: boolean
/// - `promptText`: string (optional)
pub const HANDLE_JAVA_SCRIPT_DIALOG: &str = "Page.handleJavaScriptDialog";

/// Navigates current page to the given URL.
///
/// Parameters:
/// - `url`: string
/// - `referrer`: string (optional)
/// - `transitionType`: TransitionType (optional)
/// - `frameId`: FrameId (optional)
/// - `referrerPolicy`: ReferrerPolicy (optional)
///
/// Returns: `frameId`, `loaderId`, `errorText`, `isDownload`
pub const NAVIGATE: &str = "Page.navigate";

/// Navigates current page to the given history entry.
///
/// Parameters:
/// - `entryId`: integer
pub const NAVIGATE_TO_HISTORY_ENTRY: &str = "Page.navigateToHistoryEntry";

/// Print page as PDF.
///
/// Parameters:
/// - `landscape`: boolean (optional)
/// - `displayHeaderFooter`: boolean (optional)
/// - `printBackground`: boolean (optional)
/// - `scale`: number (optional)
/// - `paperWidth`: number (optional)
/// - `paperHeight`: number (optional)
/// - `marginTop`: number (optional)
/// - `marginBottom`: number (optional)
/// - `marginLeft`: number (optional)
/// - `marginRight`: number (optional)
/// - `pageRanges`: string (optional)
/// - `headerTemplate`: string (optional)
/// - `footerTemplate`: string (optional)
/// - `preferCSSPageSize`: boolean (optional)
/// - `transferMode`: string (optional)
/// - `generateTaggedPDF`: boolean (optional)
/// - `generateDocumentOutline`: boolean (optional)
///
/// Returns: `data`, `stream`
pub const PRINT_TO_PDF: &str = "Page.printToPDF";

/// Reloads given page optionally ignoring the cache.
///
/// Parameters:
/// - `ignoreCache`: boolean (optional)
/// - `scriptToEvaluateOnLoad`: string (optional)
/// - `loaderId`: Network.LoaderId (optional)
pub const RELOAD: &str = "Page.reload";

/// Deprecated, please use removeScriptToEvaluateOnNewDocument instead.
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
///
/// Parameters:
/// - `identifier`: ScriptIdentifier
pub const REMOVE_SCRIPT_TO_EVALUATE_ON_LOAD: &str = "Page.removeScriptToEvaluateOnLoad";

/// Removes given script from the list.
///
/// Parameters:
/// - `identifier`: ScriptIdentifier
pub const REMOVE_SCRIPT_TO_EVALUATE_ON_NEW_DOCUMENT: &str =
    "Page.removeScriptToEvaluateOnNewDocument";

/// Acknowledges that a screencast frame has been received by the frontend.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `sessionId`: integer
pub const SCREENCAST_FRAME_ACK: &str = "Page.screencastFrameAck";

/// Searches for given string in resource content.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `frameId`: FrameId
/// - `url`: string
/// - `query`: string
/// - `caseSensitive`: boolean (optional)
/// - `isRegex`: boolean (optional)
///
/// Returns: `result`
pub const SEARCH_IN_RESOURCE: &str = "Page.searchInResource";

/// Enable Chrome's experimental ad filter on all sites.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `enabled`: boolean
pub const SET_AD_BLOCKING_ENABLED: &str = "Page.setAdBlockingEnabled";

/// Enable page Content Security Policy by-passing.
///
/// Parameters:
/// - `enabled`: boolean
pub const SET_BYPASS_CSP: &str = "Page.setBypassCSP";

/// Get Permissions Policy state on given frame.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `frameId`: FrameId
///
/// Returns: `states`
pub const GET_PERMISSIONS_POLICY_STATE: &str = "Page.getPermissionsPolicyState";

/// Get Origin Trials on given frame.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `frameId`: FrameId
///
/// Returns: `originTrials`
pub const GET_ORIGIN_TRIALS: &str = "Page.getOriginTrials";

/// Overrides the values of device screen dimensions (window.screen.width,
/// window.screen.height, window.innerWidth, window.innerHeight, and
/// "device-width"/"device-height"-related CSS media query results).
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
///
/// Parameters:
/// - `width`: integer
/// - `height`: integer
/// - `deviceScaleFactor`: number
/// - `mobile`: boolean
/// - `scale`: number (optional)
/// - `screenWidth`: integer (optional)
/// - `screenHeight`: integer (optional)
/// - `positionX`: integer (optional)
/// - `positionY`: integer (optional)
/// - `dontSetVisibleSize`: boolean (optional)
/// - `screenOrientation`: Emulation.ScreenOrientation (optional)
/// - `viewport`: Viewport (optional)
pub const SET_DEVICE_METRICS_OVERRIDE: &str = "Page.setDeviceMetricsOverride";

/// Overrides the Device Orientation.
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
///
/// Parameters:
/// - `alpha`: number
/// - `beta`: number
/// - `gamma`: number
pub const SET_DEVICE_ORIENTATION_OVERRIDE: &str = "Page.setDeviceOrientationOverride";

/// Set generic font families.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `fontFamilies`: FontFamilies
/// - `forScripts`: array (optional)
pub const SET_FONT_FAMILIES: &str = "Page.setFontFamilies";

/// Set default font sizes.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `fontSizes`: FontSizes
pub const SET_FONT_SIZES: &str = "Page.setFontSizes";

/// Sets given markup as the document's HTML.
///
/// Parameters:
/// - `frameId`: FrameId
/// - `html`: string
pub const SET_DOCUMENT_CONTENT: &str = "Page.setDocumentContent";

/// Set the behavior when downloading a file.
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
///
/// Parameters:
/// - `behavior`: string
/// - `downloadPath`: string (optional)
pub const SET_DOWNLOAD_BEHAVIOR: &str = "Page.setDownloadBehavior";

/// Overrides the Geolocation Position or Error. Omitting any of the
/// parameters emulates position unavailable.
///
/// Deprecated in the protocol.
///
/// Parameters:
/// - `latitude`: number (optional)
/// - `longitude`: number (optional)
/// - `accuracy`: number (optional)
pub const SET_GEOLOCATION_OVERRIDE: &str = "Page.setGeolocationOverride";

/// Controls whether page will emit lifecycle events.
///
/// Parameters:
/// - `enabled`: boolean
pub const SET_LIFECYCLE_EVENTS_ENABLED: &str = "Page.setLifecycleEventsEnabled";

/// Toggles mouse event-based touch event emulation.
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
///
/// Parameters:
/// - `enabled`: boolean
/// - `configuration`: string (optional)
pub const SET_TOUCH_EMULATION_ENABLED: &str = "Page.setTouchEmulationEnabled";

/// Starts sending each frame using the `screencastFrame` event.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `format`: string (optional)
/// - `quality`: integer (optional)
/// - `maxWidth`: integer (optional)
/// - `maxHeight`: integer (optional)
/// - `everyNthFrame`: integer (optional)
pub const START_SCREENCAST: &str = "Page.startScreencast";

/// Starts screencast video recording.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `audio`: boolean (optional)
/// - `maxWidth`: integer (optional)
/// - `maxHeight`: integer (optional)
/// - `frameRate`: integer (optional)
///
/// Returns: `stream`
pub const START_SCREEN_RECORDING: &str = "Page.startScreenRecording";

/// Stops screencast video recording.
///
/// Experimental: may change without notice.
///
/// Returns: `stream`
pub const STOP_SCREEN_RECORDING: &str = "Page.stopScreenRecording";

/// Force the page stop all navigations and pending resource fetches.
pub const STOP_LOADING: &str = "Page.stopLoading";

/// Crashes renderer on the IO thread, generates minidumps.
///
/// Experimental: may change without notice.
pub const CRASH: &str = "Page.crash";

/// Tries to close page, running its beforeunload hooks, if any.
pub const CLOSE: &str = "Page.close";

/// Tries to update the web lifecycle state of the page. It will transition
/// the page to the given state according to:
/// <https://github.com/WICG/web-lifecycle/>
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `state`: string
pub const SET_WEB_LIFECYCLE_STATE: &str = "Page.setWebLifecycleState";

/// Stops sending each frame in the `screencastFrame`.
///
/// Experimental: may change without notice.
pub const STOP_SCREENCAST: &str = "Page.stopScreencast";

/// Requests backend to produce compilation cache for the specified scripts.
/// `scripts` are appended to the list of scripts for which the cache would be
/// produced. The list may be reset during page navigation. When script with a
/// matching URL is encountered, the cache is optionally produced upon backend
/// discretion, based on internal heuristics. See also:
/// `Page.compilationCacheProduced`.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `scripts`: array
pub const PRODUCE_COMPILATION_CACHE: &str = "Page.produceCompilationCache";

/// Seeds compilation cache for given url. Compilation cache does not survive
/// cross-process navigation.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `url`: string
/// - `data`: string
pub const ADD_COMPILATION_CACHE: &str = "Page.addCompilationCache";

/// Clears seeded compilation cache.
///
/// Experimental: may change without notice.
pub const CLEAR_COMPILATION_CACHE: &str = "Page.clearCompilationCache";

/// Sets the Secure Payment Confirmation transaction mode.
/// <https://w3c.github.io/secure-payment-confirmation/#sctn-automation-set-spc-transaction-mode>
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `mode`: string
pub const SET_SPC_TRANSACTION_MODE: &str = "Page.setSPCTransactionMode";

/// Extensions for Custom Handlers API:
/// <https://html.spec.whatwg.org/multipage/system-state.html#rph-automation>
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `mode`: string
pub const SET_RPH_REGISTRATION_MODE: &str = "Page.setRPHRegistrationMode";

/// Generates a report for testing.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `message`: string
/// - `group`: string (optional)
pub const GENERATE_TEST_REPORT: &str = "Page.generateTestReport";

/// Pauses page execution. Can be resumed using generic
/// Runtime.runIfWaitingForDebugger.
///
/// Experimental: may change without notice.
pub const WAIT_FOR_DEBUGGER: &str = "Page.waitForDebugger";

/// Intercept file chooser requests and transfer control to protocol clients.
/// When file chooser interception is enabled, native file chooser dialog is
/// not shown. Instead, a protocol event `Page.fileChooserOpened` is emitted.
///
/// Parameters:
/// - `enabled`: boolean
/// - `cancel`: boolean (optional)
pub const SET_INTERCEPT_FILE_CHOOSER_DIALOG: &str = "Page.setInterceptFileChooserDialog";

/// Enable/disable prerendering manually. This command is a short-term
/// solution for <https://crbug.com/1440085>. See
/// <https://docs.google.com/document/d/12HVmFxYj5Jc-eJr5OmWsa2bqTJsbgGLKI6ZIyx0_wpA>
/// for more details. TODO(<https://crbug.com/1440085>): Remove this once
/// Puppeteer supports tab targets.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `isAllowed`: boolean
pub const SET_PRERENDERING_ALLOWED: &str = "Page.setPrerenderingAllowed";

/// Get the annotated page content for the main frame. This is an experimental
/// command that is subject to change.
///
/// Experimental: may change without notice.
///
/// Parameters:
/// - `includeActionableInformation`: boolean (optional)
///
/// Returns: `content`
pub const GET_ANNOTATED_PAGE_CONTENT: &str = "Page.getAnnotatedPageContent";
