// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! The `Performance` domain.
//!
//! Method names for the `Performance` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).

/// Disable collecting and reporting metrics.
pub const DISABLE: &str = "Performance.disable";

/// Enable collecting and reporting metrics.
///
/// Parameters:
/// - `timeDomain`: string (optional)
pub const ENABLE: &str = "Performance.enable";

/// Sets time domain to use for collecting and reporting duration metrics.
/// Note that this must be called before enabling metrics collection. Calling
/// this method while metrics collection is enabled returns an error.
///
/// Deprecated in the protocol.
/// Experimental: may change without notice.
///
/// Parameters:
/// - `timeDomain`: string
pub const SET_TIME_DOMAIN: &str = "Performance.setTimeDomain";

/// Retrieve current values of run-time metrics.
///
/// Returns: `metrics`
pub const GET_METRICS: &str = "Performance.getMetrics";
