// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! The `Profiler` domain.
//!
//! Method names for the `Profiler` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).

/// `Profiler.disable`
pub const DISABLE: &str = "Profiler.disable";

/// `Profiler.enable`
pub const ENABLE: &str = "Profiler.enable";

/// Collect coverage data for the current isolate. The coverage data may be
/// incomplete due to garbage collection.
///
/// Returns: `result`
pub const GET_BEST_EFFORT_COVERAGE: &str = "Profiler.getBestEffortCoverage";

/// Changes CPU profiler sampling interval. Must be called before CPU profiles
/// recording started.
///
/// Parameters:
/// - `interval`: integer
pub const SET_SAMPLING_INTERVAL: &str = "Profiler.setSamplingInterval";

/// `Profiler.start`
pub const START: &str = "Profiler.start";

/// Enable precise code coverage. Coverage data for JavaScript executed before
/// enabling precise code coverage may be incomplete. Enabling prevents
/// running optimized code and resets execution counters.
///
/// Parameters:
/// - `callCount`: boolean (optional)
/// - `detailed`: boolean (optional)
/// - `allowTriggeredUpdates`: boolean (optional)
///
/// Returns: `timestamp`
pub const START_PRECISE_COVERAGE: &str = "Profiler.startPreciseCoverage";

/// `Profiler.stop`
///
/// Returns: `profile`
pub const STOP: &str = "Profiler.stop";

/// Disable precise code coverage. Disabling releases unnecessary execution
/// count records and allows executing optimized code.
pub const STOP_PRECISE_COVERAGE: &str = "Profiler.stopPreciseCoverage";

/// Collect coverage data for the current isolate, and resets execution
/// counters. Precise code coverage needs to have started.
///
/// Returns: `result`, `timestamp`
pub const TAKE_PRECISE_COVERAGE: &str = "Profiler.takePreciseCoverage";
