// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! The SystemInfo domain defines methods and events for querying low-level
//! system information.
//!
//! Method names for the `SystemInfo` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is experimental and may change without notice.

/// Returns information about the system.
///
/// Returns: `gpu`, `modelName`, `modelVersion`, `commandLine`
pub const GET_INFO: &str = "SystemInfo.getInfo";

/// Returns information about the feature state.
///
/// Parameters:
/// - `featureState`: string
///
/// Returns: `featureEnabled`
pub const GET_FEATURE_STATE: &str = "SystemInfo.getFeatureState";

/// Returns information about all running processes.
///
/// Returns: `processInfo`
pub const GET_PROCESS_INFO: &str = "SystemInfo.getProcessInfo";
