// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! The Tethering domain defines methods and events for browser port binding.
//!
//! Method names for the `Tethering` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is experimental and may change without notice.

/// Request browser port binding.
///
/// Parameters:
/// - `port`: integer
pub const BIND: &str = "Tethering.bind";

/// Request browser port unbinding.
///
/// Parameters:
/// - `port`: integer
pub const UNBIND: &str = "Tethering.unbind";
