// @generated by `just generate-methods` from protocol/*.json.
// Do not edit by hand; edit xtask/ and regenerate.

//! This domain allows inspection of Web Audio API.
//! <https://webaudio.github.io/web-audio-api/>
//!
//! Method names for the `WebAudio` domain, for use with
//! [`CdpClient::call`](crate::CdpClient::call).
//!
//! This domain is experimental and may change without notice.

/// Enables the WebAudio domain and starts sending context lifetime events.
pub const ENABLE: &str = "WebAudio.enable";

/// Disables the WebAudio domain.
pub const DISABLE: &str = "WebAudio.disable";

/// Fetch the realtime data from the registered contexts.
///
/// Parameters:
/// - `contextId`: GraphObjectId
///
/// Returns: `realtimeData`
pub const GET_REALTIME_DATA: &str = "WebAudio.getRealtimeData";
